package l1j.server.server.construct.skill;

import javolution.util.FastMap;

public enum L1PassiveId {
	CRASH(1),
	FURY(2),
	SLAYER(3),
	ARMOR_GUARD(5),
	TITAN_LOCK(6),
	TITAN_BLICK(7),
	TITAN_MAGIC(8),
	COUNTER_BARRIER_VETERAN(10),
	ARMOR_BREAK_DESTINY(11),
	DOUBLE_BREAK_DESTINY(12),
	DESPERADO_ABSOLUTE(13),
	THUNDER_GRAB_BRAVE(14),
	FOU_SLAYER_BRAVE(15),
	AURAKIA(16),
	DARKHORSE(17),
	FINAL_BURN(18),
	RESIST_ELEMENTAL(21),
	GLORY_EARTH(22),
	INFINITI_ARMOR(23),
	INFINITI_BLICK(24),
	INFINITI_DODGE(25),
	DAMASCUS(26),
	PARADOX(27),
	GROWS(28),
	RAGE(29),
	PHANTOM_RIPER(30),
	PHANTOM_DEATH(31),
	FRAME(32),
	INFINITI_BLOOD(33),
	SURVIVE(34),
	PANTERA_SHOCK(36),
	BLOOD_TO_SOUL(38),
	IMMUNE_T0_HARM_SAINT(39),
	DESTROY_FEAR(40),
	DESTROY_HORROR(41),
	AURA(42),
	REDUCTION_ARMOR_VETERAN(43),
	RAIGING_FORCE(44),
	ILLUTION_RICH(45),
	ILLUTION_GOLEM(46),
	BURNING_SPRITS(47),
	DRESS_EVASION(48),
	LUCIFER_DESTINY(49),
	MEISTER_ACCURACY(50),
	CRUEL_CONVICTION(52),
	PRESSURE_DEATH_RECALL(53),
	DODGE_BREAK(55),
	MAELSTROM(56),
	DEADLY_STRIKE(57),
	VENGEANCE(58),
	TACTICAL_ADVANCE(59),
	INCREASE_RANGE(60),
	DRAGON_SKIN(61),
	SOLID_CARRIAGE(63),
	PRIDE(64),
	MEDITATION_BEYOND(65),
	SHADOW_ARMOR_DESTINY(66),
	SOLID_NOTE(67),
	RAMPAGE(68),
	BONE_BREAK_LAST(69),
	MOVING_ACCELERATION_LAST(71),
	DISINTEGREATE_NEMESIS(76),
	HOLY_WALK_EVOLUTION(77),
	ADVANCE_SPIRIT(78),
	GREAT_SUMMON_MONSTER(79),
	ARTERIAL_CIRCLE(80),
	PHANTOM_REQUIEM(81),
	EMPIRE_OVERLOAD(82),
	SHINING_ARMOR(83),
	MAJESTY(84),
	GIGANTIC(85),
	COUNTER_BARRIER_MASTER(86),
	SOUL_BARRIER_ARMOR(87),
	RAIGING_WEAPON(88),
	STRIKER_GALE_SHOT(89),
	DEMOLITION(90),
	BERSERK(91),
	TITAN_BEAST(92),
	TOMAHAWK_HUNTER(93),
	TRIPLE_ARROW_BOOST(94),
	FINE_SITE(95),
	MORTAL_BODY(96),
	SHADOW_STEP_CHASER(97),
	BLIND_HIDING_ASSASSIN(98),
	MOEBIUS(99),
	TYRANT_EXCUTION(100),
	CONQUEROR(101),
	FOU_SLAYER_FORCE(102),
	;
	private int _value;
	L1PassiveId(int passiveId) {
		_value = passiveId;
	}
	public int toInt(){
		return _value;
	}
	
	public static final L1PassiveId[] ARRAY = L1PassiveId.values();
	private static final FastMap<Integer, L1PassiveId> DATA;
	static {
		DATA = new FastMap<Integer, L1PassiveId>(ARRAY.length);
		for (L1PassiveId passive : ARRAY) {
			DATA.put(passive._value, passive);
		}
	}
	
	public static L1PassiveId fromInt(int id){
		return DATA.get(id);
	}
	
	public static void init(){}
}

