package l1j.server.server.model.npc;

import javolution.util.FastMap;

public enum L1NpcIdFactory {
	CAMUS(						200007,				l1j.server.server.model.npc.action.id.CamusAction.getInstance()),
	MARRY_RING(					70702,				l1j.server.server.model.npc.action.id.MarryRingAction.getInstance()),
	RABBITA(					900106,				l1j.server.server.model.npc.action.id.RabbitaAction.getInstance()),
	HYOSUE(						1000004,			l1j.server.server.model.npc.action.id.HyosueAction.getInstance()),
	EXP_GIVE(					4200018,			l1j.server.server.model.npc.action.id.ExpgiveAction.getInstance()),
	ID0(						900136,				l1j.server.server.model.npc.action.id.Id0Action.getInstance()),
	ORCFNONAME(					71038,				l1j.server.server.model.npc.action.id.OrcfnonameAction.getInstance()),
	ORCFBUWOO(					71039,				l1j.server.server.model.npc.action.id.OrcfbuwooAction.getInstance()),
	ORCFNOA(					71040,				l1j.server.server.model.npc.action.id.OrcfnoaAction.getInstance()),
	ORCFHUWOOMO(				71041,				l1j.server.server.model.npc.action.id.OrcfhuwoomoAction.getInstance()),
	ORCFBAKUMO(					71042,				l1j.server.server.model.npc.action.id.OrcfbakumoAction.getInstance()),
	ORCFBUKA(					71043,				l1j.server.server.model.npc.action.id.OrcfbukaAction.getInstance()),
	ORCFKAME(					71044,				l1j.server.server.model.npc.action.id.OrcfkameAction.getInstance()),
	USENDER(					71078,				l1j.server.server.model.npc.action.id.UsenderAction.getInstance()),
	AMISOO(						71080,				l1j.server.server.model.npc.action.id.AmisooAction.getInstance()),
	BETRAY_BARLOG(				80049,				l1j.server.server.model.npc.action.id.BetrayBarlogAction.getInstance()),
	MEET_BARLOG(				80050,				l1j.server.server.model.npc.action.id.MeetBarlogAction.getInstance()),
	U_HUNT(						80052,				l1j.server.server.model.npc.action.id.UhuntAction.getInstance()),
	U_AMULET(					80055,				l1j.server.server.model.npc.action.id.UamuletAction.getInstance()),
	INFAMOUS_BARLOG(			80056,				l1j.server.server.model.npc.action.id.InfamousBarlogAction.getInstance()),
	MEET_YAHEE(					80064,				l1j.server.server.model.npc.action.id.MeetYaheeAction.getInstance()),
	BETRAY_YAHEE(				80066,				l1j.server.server.model.npc.action.id.BetrayYaheeAction.getInstance()),
	L_RING(						80071,				l1j.server.server.model.npc.action.id.LringAction.getInstance()),
	L_HUNT(						80073,				l1j.server.server.model.npc.action.id.LhuntAction.getInstance()),
	TEBE_GATE(					205,				l1j.server.server.model.npc.action.id.TebegateAction.getInstance()),
	COMA(						7000021,			l1j.server.server.model.npc.action.id.ComaAction.getInstance()),
	JOE_GOLEM(					500062,				l1j.server.server.model.npc.action.id.JoegolemAction.getInstance()),
	TIKAL_GATE(					500063,				l1j.server.server.model.npc.action.id.TikalgateAction.getInstance()),
	ITEXPLORER(					500064,				l1j.server.server.model.npc.action.id.ItexplorerAction.getInstance()),
	INFAMOUS_YAHEE(				80074,				l1j.server.server.model.npc.action.id.InfamousYaheeAction.getInstance()),
	ESMERELD(					50007,				l1j.server.server.model.npc.action.id.EsmereldAction.getInstance()),
	WPASS_1(					80059,				l1j.server.server.model.npc.action.id.DimensionDoorAction.getInstance()),
	WPASS_2(					80060,				l1j.server.server.model.npc.action.id.DimensionDoorAction.getInstance()),
	WPASS_3(					80061,				l1j.server.server.model.npc.action.id.DimensionDoorAction.getInstance()),
	WPASS_4(					80062,				l1j.server.server.model.npc.action.id.DimensionDoorAction.getInstance()),
	EN(							81124,				l1j.server.server.model.npc.action.id.EnAction.getInstance()),
	JPE_1(						71005,				l1j.server.server.model.npc.action.id.Jpe1Action.getInstance()),
	JPE_2(						71025,				l1j.server.server.model.npc.action.id.Jpe2Action.getInstance()),
	NOVED(						70512,				l1j.server.server.model.npc.action.id.NovedAction.getInstance()),
	HADESTY(					70910,				l1j.server.server.model.npc.action.id.HadestyAction.getInstance()),
	RESTA(						71060,				l1j.server.server.model.npc.action.id.RestaAction.getInstance()),
	CADMUS(						71061,				l1j.server.server.model.npc.action.id.CadmusAction.getInstance()),
	KAMYLA(						71036,				l1j.server.server.model.npc.action.id.KamylaAction.getInstance()),
	FRANCU(						71089,				l1j.server.server.model.npc.action.id.FrancuAction.getInstance()),
	TION(						71198,				l1j.server.server.model.npc.action.id.TionAction.getInstance()),
	JERON(						71199,				l1j.server.server.model.npc.action.id.JeronAction.getInstance()),
	JP(							71180,				l1j.server.server.model.npc.action.id.JpAction.getInstance()),
	MY(							71181,				l1j.server.server.model.npc.action.id.MyAction.getInstance()),
	ISVAL(						70086,				l1j.server.server.model.npc.action.id.IsvalAction.getInstance()),
	RPARUM(						80084,				l1j.server.server.model.npc.action.id.RparumAction.getInstance()),
	CROWN_HELMET(				80105,				l1j.server.server.model.npc.action.id.CrownHelmetAction.getInstance()),
	FEAENA(						4202000,			l1j.server.server.model.npc.action.id.FeaenaAction.getInstance()),
	ASHA(						4201000,			l1j.server.server.model.npc.action.id.AshaAction.getInstance()),
	CANDLEG(					200015,				l1j.server.server.model.npc.action.id.CandlegAction.getInstance()),
	PROKEL(						3000003,			l1j.server.server.model.npc.action.id.ProkelAction.getInstance()),
	SILREIN(					3100004,			l1j.server.server.model.npc.action.id.SilreinAction.getInstance()),
	SHARNA(						200075,				l1j.server.server.model.npc.action.id.SharnaAction.getInstance()),
	ERIS(						71126,				l1j.server.server.model.npc.action.id.ErisAction.getInstance()),
	MINICOD(					80067,				l1j.server.server.model.npc.action.id.MinicodAction.getInstance()),
	SUS_CHEF(					900048,				l1j.server.server.model.npc.action.id.SuschefAction.getInstance()),
	MARBA(						70842,				l1j.server.server.model.npc.action.id.MarbaAction.getInstance()),
	MINITOS(					81202,				l1j.server.server.model.npc.action.id.MinitosAction.getInstance()),
	TUTORRW(					9274,				l1j.server.server.model.npc.action.id.TutorrwAction.getInstance()),
	HPASS(						900186,				l1j.server.server.model.npc.action.id.HpassAction.getInstance()),
	HIGH_DAILY(					900187,				l1j.server.server.model.npc.action.id.HighdailyAction.getInstance()),
	MAENO_1(					70035,				l1j.server.server.model.npc.action.id.MaenoAction.getInstance()),
	MAENO_2(					70041,				l1j.server.server.model.npc.action.id.MaenoAction.getInstance()),
	MAENO_3(					70042,				l1j.server.server.model.npc.action.id.MaenoAction.getInstance()),
	MAENO_4(					170041,				l1j.server.server.model.npc.action.id.MaenoAction.getInstance()),
	KILLTON(					777849,				l1j.server.server.model.npc.action.id.KilltonAction.getInstance()),
	MERIN(						777848,				l1j.server.server.model.npc.action.id.MerinAction.getInstance()),
	HIGH_DAILY_B(				900188,				l1j.server.server.model.npc.action.id.HighdailybAction.getInstance()),
	NEW_BRAD(					70751,				l1j.server.server.model.npc.action.id.NewbradAction.getInstance()),
	MARBIN_QUEST(				70000,				l1j.server.server.model.npc.action.id.MarbinquestAction.getInstance()),
	PIERS(						70908,				l1j.server.server.model.npc.action.id.PiersAction.getInstance()),
	ICQWAND(					5086,				l1j.server.server.model.npc.action.id.IcqwandAction.getInstance()),
	VETERAN(					5111,				l1j.server.server.model.npc.action.id.VeteranAction.getInstance()),
	LIND_SM(					5112,				l1j.server.server.model.npc.action.id.LindSmAction.getInstance()),
	CANUS(						5125,				l1j.server.server.model.npc.action.id.CanusAction.getInstance()),
	BS_TOWN_BUFF_1(				900088,				l1j.server.server.model.npc.action.id.BsTownBuffAction.getInstance()),
	BS_TOWN_BUFF_2(				7310100,			l1j.server.server.model.npc.action.id.BsTownBuffAction.getInstance()),
	BS_TOWN_BUFF_3(				5001,				l1j.server.server.model.npc.action.id.BsTownBuffAction.getInstance()),
	BS_TOWN_BUFF_4(				5002,				l1j.server.server.model.npc.action.id.BsTownBuffAction.getInstance()),
	BS_TOWN_BUFF_5(				5003,				l1j.server.server.model.npc.action.id.BsTownBuffAction.getInstance()),
	BS_TOWN_BUFF_6(				5004,				l1j.server.server.model.npc.action.id.BsTownBuffAction.getInstance()),
	BS_TOWN_BUFF_7(				5005,				l1j.server.server.model.npc.action.id.BsTownBuffAction.getInstance()),
	BS_TOWN_BUFF_8(				5006,				l1j.server.server.model.npc.action.id.BsTownBuffAction.getInstance()),
	BS_TOWN_BUFF_9(				5007,				l1j.server.server.model.npc.action.id.BsTownBuffAction.getInstance()),
	BS_TOWN_BUFF_10(			5008,				l1j.server.server.model.npc.action.id.BsTownBuffAction.getInstance()),
	BS_TOWN_BUFF_11(			5009,				l1j.server.server.model.npc.action.id.BsTownBuffAction.getInstance()),
	BS_TOWN_BUFF_12(			5011,				l1j.server.server.model.npc.action.id.BsTownBuffAction.getInstance()),
	BS_TOWN_BUFF_13(			5012,				l1j.server.server.model.npc.action.id.BsTownBuffAction.getInstance()),
	BS_TOWN_BUFF_14(			5016,				l1j.server.server.model.npc.action.id.BsTownBuffAction.getInstance()),
	BS_TOWN_BUFF_15(			7220064,			l1j.server.server.model.npc.action.id.BsTownBuffAction.getInstance()),
	BS_TOWN_BUFF_16(			800166,				l1j.server.server.model.npc.action.id.BsTownBuffAction.getInstance()),
	BS_TOWN_BUFF_17(			5173,				l1j.server.server.model.npc.action.id.BsTownBuffAction.getInstance()),
	BS_TOWN_BUFF_18(			900515,				l1j.server.server.model.npc.action.id.BsTownBuffAction.getInstance()),
	BS_TOWN_BUFF_19(			70102,				l1j.server.server.model.npc.action.id.BsTownBuffAction.getInstance()),
	BS_TOWN_BUFF_20(			71003,				l1j.server.server.model.npc.action.id.BsTownBuffAction.getInstance()),
	BS_TER_BUFF(				5000,				l1j.server.server.model.npc.action.id.BsTerBuffAction.getInstance()),
	BS_S_BUFF(					5010,				l1j.server.server.model.npc.action.id.BssBuffAction.getInstance()),
	I_BS_BUFF_1(				800520,				l1j.server.server.model.npc.action.id.IbsBuffAction.getInstance()),
	I_BS_BUFF_2(				800521,				l1j.server.server.model.npc.action.id.IbsBuffAction.getInstance()),
	I_BS_BUFF_3(				800522,				l1j.server.server.model.npc.action.id.IbsBuffAction.getInstance()),
	I_BS_BUFF_4(				800523,				l1j.server.server.model.npc.action.id.IbsBuffAction.getInstance()),
	I_BS_BUFF_5(				800524,				l1j.server.server.model.npc.action.id.IbsBuffAction.getInstance()),
	I_BS_BUFF_6(				800525,				l1j.server.server.model.npc.action.id.IbsBuffAction.getInstance()),
	I_BS_BUFF_7(				800526,				l1j.server.server.model.npc.action.id.IbsBuffAction.getInstance()),
	I_BS_BUFF_8(				800527,				l1j.server.server.model.npc.action.id.IbsBuffAction.getInstance()),
	BS_GTW_BUFF_1(				800802,				l1j.server.server.model.npc.action.id.BsGtwBuffAction.getInstance()),
	BS_GTW_BUFF_2(				800805,				l1j.server.server.model.npc.action.id.BsGtwBuffAction.getInstance()),
	BS_GTW_BUFF_3(				800808,				l1j.server.server.model.npc.action.id.BsGtwBuffAction.getInstance()),
	METIS_BUFF(					750067,				l1j.server.server.model.npc.action.id.MetisBuffAction.getInstance()),
	HIGH_LEVEL_BUFF(			750066,				l1j.server.server.model.npc.action.id.HighlevelBuffAction.getInstance()),
	LEVEL100_BUFF(				750068,				l1j.server.server.model.npc.action.id.Level100BuffAction.getInstance()),
	ELF_ATTR_1(					70760,				l1j.server.server.model.npc.action.id.ElfAttrAction.getInstance()),
	ELF_ATTR_2(					9291,				l1j.server.server.model.npc.action.id.ElfAttrAction.getInstance()),
	ELF_ATTR_3(					9292,				l1j.server.server.model.npc.action.id.ElfAttrAction.getInstance()),
	KAIZER(						7000079,			l1j.server.server.model.npc.action.id.KaizerAction.getInstance()),
	BOSS_KEY(					7000080,			l1j.server.server.model.npc.action.id.BossKeyAction.getInstance()),
	YURIS(						4213001,			l1j.server.server.model.npc.action.id.YurisAction.getInstance()),
	BIRTHDAY(					7200022,			l1j.server.server.model.npc.action.id.BirthdayAction.getInstance()),
	OLD_BOOK(					7210050,			l1j.server.server.model.npc.action.id.OldbookAction.getInstance()),
	ALTAR(						80094,				l1j.server.server.model.npc.action.id.AltarAction.getInstance()),
	GIANT_TOMB_1(				7210047,			l1j.server.server.model.npc.action.id.GiantTombAction.getInstance()),
	GIANT_TOMB_2(				7210048,			l1j.server.server.model.npc.action.id.GiantTombAction.getInstance()),
	GR_MAMMON(					6000014,			l1j.server.server.model.npc.action.id.GrMammonAction.getInstance()),
	VOYAGER(					80076,				l1j.server.server.model.npc.action.id.VoyagerAction.getInstance()),
	ARCH_GUNTER(				202065,				l1j.server.server.model.npc.action.id.ArchgunterAction.getInstance()),
	RIDDLE(						7000055,			l1j.server.server.model.npc.action.id.RiddleAction.getInstance()),
	SEIRUNE(					7000054,			l1j.server.server.model.npc.action.id.SeiruneAction.getInstance()),
	HAMO(						7210007,			l1j.server.server.model.npc.action.id.HamoAction.getInstance()),
	ELDNAS(						7210008,			l1j.server.server.model.npc.action.id.EldnasAction.getInstance()),
	FD_DEATH(					7210009,			l1j.server.server.model.npc.action.id.FdDeathAction.getInstance()),
	GRAY_KNIGHT(				7200026,			l1j.server.server.model.npc.action.id.GrayknightAction.getInstance()),
	SHAMANSAEL(					4039009,			l1j.server.server.model.npc.action.id.ShamansaelAction.getInstance()),
	GUNTERDG(					60169,				l1j.server.server.model.npc.action.id.GunterdgAction.getInstance()),
	VDEATH(						7311159,			l1j.server.server.model.npc.action.id.VdeathAction.getInstance()),
	HALPAS_JAKEN(				900512,				l1j.server.server.model.npc.action.id.HalpasJakenAction.getInstance()),
	WORLD_WAR_ENTER_1(			800500,				l1j.server.server.model.npc.action.id.WorldWarEnterAction.getInstance()),
	WORLD_WAR_ENTER_2(			800528,				l1j.server.server.model.npc.action.id.WorldWarEnterAction.getInstance()),
	WORLD_WAR_ENTER_3(			800529,				l1j.server.server.model.npc.action.id.WorldWarEnterAction.getInstance()),
	WORLD_WAR_ENTER_4(			800530,				l1j.server.server.model.npc.action.id.WorldWarEnterAction.getInstance()),
	GTW_INTER_TEL_1(			800809,				l1j.server.server.model.npc.action.id.GtwInterTelAction.getInstance()),
	GTW_INTER_TEL_2(			800810,				l1j.server.server.model.npc.action.id.GtwInterTelAction.getInstance()),
	GTW_ENTER_TEL_1(			800800,				l1j.server.server.model.npc.action.id.GtwEnterAction.getInstance()),
	GTW_ENTER_TEL_2(			800803,				l1j.server.server.model.npc.action.id.GtwEnterAction.getInstance()),
	GTW_ENTER_TEL_3(			800806,				l1j.server.server.model.npc.action.id.GtwEnterAction.getInstance()),
	GTW_ENTER_TEL_4(			800819,				l1j.server.server.model.npc.action.id.GtwEnterAction.getInstance()),
	GTW_ENTER_TEL_5(			800820,				l1j.server.server.model.npc.action.id.GtwEnterAction.getInstance()),
	GTW_ENTER_TEL_6(			800821,				l1j.server.server.model.npc.action.id.GtwEnterAction.getInstance()),
	RUUN_CASTLE(				70109,				l1j.server.server.model.npc.action.id.RuunCastleAction.getInstance()),
	OMAN_TELEPORT(				7230012,			l1j.server.server.model.npc.action.id.OmanTeleportAction.getInstance()),
	HI_COLOS(					150035,				l1j.server.server.model.npc.action.id.HiColosAction.getInstance()),
	WCD_ENTER(					5172,				l1j.server.server.model.npc.action.id.WcdEnterAction.getInstance()),
	WCD_POLY(					5175,				l1j.server.server.model.npc.action.id.WcdPolyAction.getInstance()),
	ABANDON(					146055,				l1j.server.server.model.npc.action.id.AbandonAction.getInstance()),
	INTER_ABANDON_WEST(			146060,				l1j.server.server.model.npc.action.id.AbandonAction.getInstance()),
	INTER_ABANDON_EAST(			146068,				l1j.server.server.model.npc.action.id.AbandonAction.getInstance()),
	CHAOTIC_D(					7220080,			l1j.server.server.model.npc.action.id.ChaoticDAction.getInstance()),
	GERENG_QUEST(				700099,				l1j.server.server.model.npc.action.id.GerengQuestAction.getInstance()),
	BACK_TO_GUNTER(				201076,				l1j.server.server.model.npc.action.id.BacktogunterAction.getInstance()),
	DOMINATION_TOWER_ENTER_1(	800101,				l1j.server.server.model.npc.action.id.DominationTowerEnterAction.getInstance()),
	DOMINATION_TOWER_ENTER_2(	800102,				l1j.server.server.model.npc.action.id.DominationTowerEnterAction.getInstance()),
	DOMINATION_TOWER_ENTER_3(	800103,				l1j.server.server.model.npc.action.id.DominationTowerEnterAction.getInstance()),
	DOMINATION_TOWER_ENTER_4(	800104,				l1j.server.server.model.npc.action.id.DominationTowerEnterAction.getInstance()),
	DOMINATION_TOWER_ENTER_5(	800105,				l1j.server.server.model.npc.action.id.DominationTowerEnterAction.getInstance()),
	DOMINATION_TOWER_ENTER_6(	800106,				l1j.server.server.model.npc.action.id.DominationTowerEnterAction.getInstance()),
	DOMINATION_TOWER_ENTER_7(	800107,				l1j.server.server.model.npc.action.id.DominationTowerEnterAction.getInstance()),
	DOMINATION_TOWER_ENTER_8(	800108,				l1j.server.server.model.npc.action.id.DominationTowerEnterAction.getInstance()),
	DOMINATION_TOWER_ENTER_9(	800109,				l1j.server.server.model.npc.action.id.DominationTowerEnterAction.getInstance()),
	DOMINATION_TOWER_ENTER_10(	800110,				l1j.server.server.model.npc.action.id.DominationTowerEnterAction.getInstance()),
	DOMINATION_TOWER_ENTER_11(	800111,				l1j.server.server.model.npc.action.id.DominationTowerEnterAction.getInstance()),
	RIFT_WIZARD_1(				800112,				l1j.server.server.model.npc.action.id.RiftWizardAction.getInstance()),
	RIFT_WIZARD_2(				800113,				l1j.server.server.model.npc.action.id.RiftWizardAction.getInstance()),
	RIFT_WIZARD_3(				800114,				l1j.server.server.model.npc.action.id.RiftWizardAction.getInstance()),
	RIFT_WIZARD_4(				800115,				l1j.server.server.model.npc.action.id.RiftWizardAction.getInstance()),
	RIFT_WIZARD_5(				800116,				l1j.server.server.model.npc.action.id.RiftWizardAction.getInstance()),
	RIFT_WIZARD_6(				800117,				l1j.server.server.model.npc.action.id.RiftWizardAction.getInstance()),
	RIFT_WIZARD_7(				800118,				l1j.server.server.model.npc.action.id.RiftWizardAction.getInstance()),
	RIFT_WIZARD_8(				800119,				l1j.server.server.model.npc.action.id.RiftWizardAction.getInstance()),
	RIFT_WIZARD_9(				800120,				l1j.server.server.model.npc.action.id.RiftWizardAction.getInstance()),
	RIFT_WIZARD_10(				800121,				l1j.server.server.model.npc.action.id.RiftWizardAction.getInstance()),
	RIFT_WIZARD_11(				800122,				l1j.server.server.model.npc.action.id.RiftWizardAction.getInstance()),
	RIFT_WIZARD_12(				800210,				l1j.server.server.model.npc.action.id.RiftWizardAction.getInstance()),
	ID_YURIE(					900135,				l1j.server.server.model.npc.action.id.IdYurieAction.getInstance()),
	INDUN_LOSUS_GERENG(			7800100,			l1j.server.server.model.npc.action.id.IndunLosusGerengAction.getInstance()),
	J_CRYSTAL(					71090,				l1j.server.server.model.npc.action.id.JcrystalAction.getInstance()),
	J_CRYSTALL(					71091,				l1j.server.server.model.npc.action.id.JcrystallAction.getInstance()),
	FK_IN(						80082,				l1j.server.server.model.npc.action.id.FkInAction.getInstance()),
	NEW_BIE_GATE(				70798,				l1j.server.server.model.npc.action.id.NewbiegateAction.getInstance()),
	CTID_1(						7200001,			l1j.server.server.model.npc.action.id.CtidAction.getInstance()),
	CTID_2(						7200028,			l1j.server.server.model.npc.action.id.CtidAction.getInstance()),
	EKINS(						7200000,			l1j.server.server.model.npc.action.id.EkinsAction.getInstance()),
	KING_DEVSUM(				5100017,			l1j.server.server.model.npc.action.id.KingdevsumAction.getInstance()),
	ANOLD(						7,					l1j.server.server.model.npc.action.id.AnoldAction.getInstance()),
	NARUTO(						9,					l1j.server.server.model.npc.action.id.NarutoAction.getInstance()),
	CASTLE_WAR_BOMB_1(			7000082,			l1j.server.server.model.npc.action.id.CastleWarBombAction.getInstance()),
	CASTLE_WAR_BOMB_2(			7000083,			l1j.server.server.model.npc.action.id.CastleWarBombAction.getInstance()),
	CASTLE_WAR_BOMB_3(			7000084,			l1j.server.server.model.npc.action.id.CastleWarBombAction.getInstance()),
	CASTLE_WAR_BOMB_4(			7000085,			l1j.server.server.model.npc.action.id.CastleWarBombAction.getInstance()),
	CASTLE_WAR_BOMB_5(			7000086,			l1j.server.server.model.npc.action.id.CastleWarBombAction.getInstance()),
	CASTLE_WAR_BOMB_6(			7000087,			l1j.server.server.model.npc.action.id.CastleWarBombAction.getInstance()),
	C_SAINT(					100702,				l1j.server.server.model.npc.action.id.CsaintAction.getInstance()),
	C_TRAINER(					100701,				l1j.server.server.model.npc.action.id.CtrainerAction.getInstance()),
	BUF_SOLO_AGIT(				11094,				l1j.server.server.model.npc.action.id.BufSoloAgitAction.getInstance()),
	BOSS_RECALL(				11095,				l1j.server.server.model.npc.action.id.BossRecallAction.getInstance()),
	;
	
	private int _npcId;
	private L1NpcIdAction _action;
	L1NpcIdFactory(int id, L1NpcIdAction action) {
		_npcId	= id;
		_action	= action;
	}
	
	private static final FastMap<Integer, L1NpcIdAction> _actions;
	static {
		L1NpcIdFactory[] actions	= L1NpcIdFactory.values();
		_actions					= new FastMap<Integer, L1NpcIdAction>(actions.length);
		for (L1NpcIdFactory action : actions) {
			_actions.put(action._npcId, action._action);
		}
	}
	
	public static L1NpcIdAction getIdAction(int id){
		return _actions.get(id);
	}
	
	public static void init(){}
}

