package l1j.server.server.construct.message;

import l1j.server.server.serverpackets.message.S_ServerMessage;

public class L1ServerMessage {
	public static final S_ServerMessage sm53			=	new S_ServerMessage(53);// 이름이 잘못되었습니다. 다른 이름을 입력하십시오.
	public static final S_ServerMessage sm63			=	new S_ServerMessage(63);// 잘못된 능력치입니다.
	public static final S_ServerMessage sm64			=	new S_ServerMessage(64);// 서버와의 접속이 끊어졌습니다.
	public static final S_ServerMessage sm75			=	new S_ServerMessage(75);// 인벤토리에 넣을 수 있는 아이템은 최대 180개 입니다.
	public static final S_ServerMessage sm77			=	new S_ServerMessage(77);// 회복의 기운이 느껴집니다.
	public static final S_ServerMessage sm79			=	new S_ServerMessage(79);// 아무일도 일어나지 않았습니다.
	public static final S_ServerMessage sm82			=	new S_ServerMessage(82);// 무게 게이지가 부족하거나 인벤토리가 꽉차서 더 들 수 없습니다.
	public static final S_ServerMessage sm85			=	new S_ServerMessage(85);// 혈맹: 창설 불가(군주만 가능함)
	public static final S_ServerMessage sm86			=	new S_ServerMessage(86);// 혈맹: 창설 불가(이미 혈맹을 창설한 상태)
	public static final S_ServerMessage sm87			=	new S_ServerMessage(87);// 다른 혈맹에 가입하다니요! 당신은 왕자입니다!
	public static final S_ServerMessage sm88			=	new S_ServerMessage(88);// 다른 혈맹에 가입하다니요! 당신은 공주입니다!
	public static final S_ServerMessage sm89			=	new S_ServerMessage(89);// 혈맹: 이미 혈맹에 가입한 상태
	public static final S_ServerMessage sm93			=	new S_ServerMessage(93);// 그 곳에는 아무도 없습니다.
	public static final S_ServerMessage sm98			=	new S_ServerMessage(98);// 혈맹: 창설 불가(혈맹 이름 최대 16byte)
	public static final S_ServerMessage sm99			=	new S_ServerMessage(99);// 혈맹: 창설 불가(동일 혈맹 이름 존재)
	public static final S_ServerMessage sm110			=	new S_ServerMessage(110);// 무게 게이지가 82%를 넘어 공격을 할 수 없습니다.
	public static final S_ServerMessage sm111			=	new S_ServerMessage(111);// 커스-페럴라이즈: 석화 상태(마비)
	public static final S_ServerMessage sm112			=	new S_ServerMessage(112);// 다시 움직일 수 있게 되었습니다.
	public static final S_ServerMessage sm124			=	new S_ServerMessage(124);// 같은 슬롯에 이미 아이템을 착용하고 있습니다.
	public static final S_ServerMessage sm125			=	new S_ServerMessage(125);// 착용한 아이템이거나 교환 불가 또는 봉인 상태입니다.
	public static final S_ServerMessage sm128			=	new S_ServerMessage(128);// 방패를 해제 한 후 양손 무기를 착용 해주세요.
	public static final S_ServerMessage sm129			=	new S_ServerMessage(129);// 양손 무기를 해제 한 후 방패를 착용 해주세요.
	public static final S_ServerMessage sm130			=	new S_ServerMessage(130);// 아직 전투 중이라 접속을 끊을 수 없습니다.
	public static final S_ServerMessage sm131			=	new S_ServerMessage(131);// 아직 전투 중이라 그만둘 수 없습니다.
	public static final S_ServerMessage sm141			=	new S_ServerMessage(141);// 교환 불가 및 봉인 상태 또는 착용한 아이템은 줄 수 없습니다.
	public static final S_ServerMessage sm142			=	new S_ServerMessage(142);// 아이템을 줄 대상과 좀 더 가까워야 합니다.
	public static final S_ServerMessage sm144			=	new S_ServerMessage(144);// 슬롯에 이미 아이템을 착용하고 있습니다.
	public static final S_ServerMessage sm150			=	new S_ServerMessage(150);// 저주를 풀어야 착용을 해제 할 수 있습니다.
	public static final S_ServerMessage sm152			=	new S_ServerMessage(152);// 이제 눈멀기 물약을 사용해 광원을 볼 수 있습니다.
	public static final S_ServerMessage sm153			=	new S_ServerMessage(153);// 채팅 금지: 채팅을 할 수 없음(2분)
	public static final S_ServerMessage sm155			=	new S_ServerMessage(155);// 저주를 풀었습니다.
	public static final S_ServerMessage sm156			=	new S_ServerMessage(156);// 손이 실룩거립니다.
	public static final S_ServerMessage sm157			=	new S_ServerMessage(157);// 손이 근질거립니다.
	public static final S_ServerMessage sm167			=	new S_ServerMessage(167);// 갑옷 파괴 주문: 착용한 방어구가 없습니다.
	public static final S_ServerMessage sm168			=	new S_ServerMessage(168);// 갑옷 파괴 주문: 망토가 증발 하였습니다.
	public static final S_ServerMessage sm169			=	new S_ServerMessage(169);// 갑옷 파괴 주문: 갑옷이 증발 하였습니다.
	public static final S_ServerMessage sm170			=	new S_ServerMessage(170);// 갑옷 파괴 주문: 티셔츠가 증발 하였습니다.
	public static final S_ServerMessage sm171			=	new S_ServerMessage(171);// 갑옷 파괴 주문: 투구가 증발 하였습니다.
	public static final S_ServerMessage sm172			=	new S_ServerMessage(172);// 갑옷 파괴 주문: 장갑이 증발 하였습니다.
	public static final S_ServerMessage sm173			=	new S_ServerMessage(173);// 갑옷 파괴 주문: 장화가 증발 하였습니다.
	public static final S_ServerMessage sm174			=	new S_ServerMessage(174);// 갑옷 파괴 주문: 방패가 증발 하였습니다.
	public static final S_ServerMessage sm176			=	new S_ServerMessage(176);// 기분이 매우 좋아졌습니다.
	public static final S_ServerMessage sm181			=	new S_ServerMessage(181);// 지금은 그 변신을 할 수 없습니다.
	public static final S_ServerMessage sm185			=	new S_ServerMessage(185);// 가속 효과가 사라집니다.
	public static final S_ServerMessage sm189			=	new S_ServerMessage(189);// 아데나가 부족합니다.
	public static final S_ServerMessage sm196			=	new S_ServerMessage(196);// 사용법: /호칭 [캐릭터명][원하는 호칭]
	public static final S_ServerMessage sm197			=	new S_ServerMessage(197);// 호칭: 부여 불가(혈맹원이 10레벨 미만)
	public static final S_ServerMessage sm198			=	new S_ServerMessage(198);// 호칭: 부여 불가(군주 또는 부군주가 아님)
	public static final S_ServerMessage sm199			=	new S_ServerMessage(199);// 호칭: 부여 불가(같은 혈맹원이 아님)
	public static final S_ServerMessage sm200			=	new S_ServerMessage(200);// 호칭: 부여 불가(40레벨 미만)
	public static final S_ServerMessage sm202			=	new S_ServerMessage(202);// 호칭: 부여 불가(혈맹원이 10레벨 미만)
	public static final S_ServerMessage sm208			=	new S_ServerMessage(208);// 창고: 혈맹 창고 이용 불가(혈맹 미가입)
	public static final S_ServerMessage sm209			=	new S_ServerMessage(209);// 창고: 혈맹 창고 사용 대기중
	public static final S_ServerMessage sm211			=	new S_ServerMessage(211);// 해독: 독을 해제함
	public static final S_ServerMessage sm212			=	new S_ServerMessage(212);// 커스-페럴라이즈: 석화 상태(진행 중)
	public static final S_ServerMessage sm213			=	new S_ServerMessage(213);// 커스-페럴라이즈: 석화 상태(마비)
	public static final S_ServerMessage sm214			=	new S_ServerMessage(214);// 여기를 기억할 수가 없습니다.
	public static final S_ServerMessage sm230			=	new S_ServerMessage(230);// 랜턴에 기름을 새로 채웠습니다.
	public static final S_ServerMessage sm232			=	new S_ServerMessage(232);// 레벨 15 이하의 군주는 선전포고할 수 없습니다.
	public static final S_ServerMessage sm234			=	new S_ServerMessage(234);// 당신의 혈맹은 벌써 전쟁중입니다.
	public static final S_ServerMessage sm242			=	new S_ServerMessage(242);// 현재 채팅 금지중입니다.
	public static final S_ServerMessage sm255			=	new S_ServerMessage(255);// 교환: 아이템 교환은 한 번에 16개까지 가능함
	public static final S_ServerMessage sm256			=	new S_ServerMessage(256);// 교환: 취소됨
	public static final S_ServerMessage sm257			=	new S_ServerMessage(257);// 교환: 완료됨
	public static final S_ServerMessage sm258			=	new S_ServerMessage(258);// 교환: 이미 다른 캐릭터와 교환중
	public static final S_ServerMessage sm259			=	new S_ServerMessage(259);// 교환: 현재 다른 캐릭터와 교환중
	public static final S_ServerMessage sm260			=	new S_ServerMessage(260);// 사용법: /교환(상대와 마주 본 상태)
	public static final S_ServerMessage sm261			=	new S_ServerMessage(261);// 명령어를 잘못 입력했습니다.
	public static final S_ServerMessage sm263			=	new S_ServerMessage(263);// 인벤토리에 넣을 수 있는 아이템은 최대 180개 입니다.
	public static final S_ServerMessage sm264			=	new S_ServerMessage(264);// 당신의 클래스에서는 이 아이템은 사용할 수 없습니다.
	public static final S_ServerMessage sm270			=	new S_ServerMessage(270);// 교환: 불가(자신의 무게 게이지가 부족함)
	public static final S_ServerMessage sm271			=	new S_ServerMessage(271);// 교환: 불가(상대의 무게 게이지가 부족함)
	public static final S_ServerMessage sm272			=	new S_ServerMessage(272);// 전쟁: 선포 불가(혈맹 미창설)
	public static final S_ServerMessage sm276			=	new S_ServerMessage(276);// 이 곳은 무작위 텔레포트를 할 수 없는 지역입니다.
	public static final S_ServerMessage sm278			=	new S_ServerMessage(278);// MP가 부족해 마법을 사용할 수 있지 않습니다.
	public static final S_ServerMessage sm279			=	new S_ServerMessage(279);// HP가 부족해 마법을 사용할 수 있지 않습니다.
	public static final S_ServerMessage sm280			=	new S_ServerMessage(280);// 마법 사용: 실패(성공하지 못함)
	public static final S_ServerMessage sm281			=	new S_ServerMessage(281);// 마법 사용: 실패(올바른 대상이 아니거나 취소함)
	public static final S_ServerMessage sm285			=	new S_ServerMessage(285);// 마법 사용: 불가(침묵 상태:마법 및 독)
	public static final S_ServerMessage sm288			=	new S_ServerMessage(288);// 채팅금지가 해재되었습니다.
	public static final S_ServerMessage sm297			=	new S_ServerMessage(297);// 가벼운 현기증을 느꼈습니다.
	public static final S_ServerMessage sm299			=	new S_ServerMessage(299);// 마법을 영창하기 위한 재료가 충분하지 않습니다.
	public static final S_ServerMessage sm302			=	new S_ServerMessage(302);// 해산할 수 없습니다.
	public static final S_ServerMessage sm305			=	new S_ServerMessage(305);// 지금은 전쟁 시간을 변경할 수 없습니다.
	public static final S_ServerMessage sm312			=	new S_ServerMessage(312);// 매직 레벨이 낮아 이 마법을 배울 수 없습니다.
	public static final S_ServerMessage sm316			=	new S_ServerMessage(316);// 무게 게이지가 82%를 넘어 마법을 쓸 수 없습니다.
	public static final S_ServerMessage sm319			=	new S_ServerMessage(319);// 더 이상의 몬스터를 조종할 수 없습니다.
	public static final S_ServerMessage sm333			=	new S_ServerMessage(333);// 지금은 이 아이템을 착용할 수 없습니다.
	public static final S_ServerMessage sm334			=	new S_ServerMessage(334);// 교환: 불가(투명 상태)
	public static final S_ServerMessage sm337_MISLIL	=	new S_ServerMessage(337, "$767");// 미스릴이 부족합니다.
	public static final S_ServerMessage sm337_GEMSTONE	=	new S_ServerMessage(337, "$5240");// 결정체가 부족합니다.
	public static final S_ServerMessage sm337_BOMB		=	new S_ServerMessage(337, "$16785");// 폭탄이 부족합니다.
	public static final S_ServerMessage sm337_FEATHER	=	new S_ServerMessage(337, "$19487");// 픽시의 금빛 깃털이 부족합니다.
	public static final S_ServerMessage sm337_KNIGHT	=	new S_ServerMessage(337, "$30202");// 기사단의 주화가 부족합니다.
	public static final S_ServerMessage sm337_RUUN		=	new S_ServerMessage(337, "$35483");// 루운성 광장 입장권이 부족합니다.
	public static final S_ServerMessage sm337_OMAN_1	=	new S_ServerMessage(337, "$12333");// 오만의 탑 1층 이동 주문서가 부족합니다.
	public static final S_ServerMessage sm337_OMAN_2	=	new S_ServerMessage(337, "$2169");// 오만의 탑 2층 이동 주문서가 부족합니다.
	public static final S_ServerMessage sm337_OMAN_3	=	new S_ServerMessage(337, "$2168");// 오만의 탑 3층 이동 주문서가 부족합니다.
	public static final S_ServerMessage sm337_OMAN_4	=	new S_ServerMessage(337, "$2404");// 오만의 탑 4층 이동 주문서가 부족합니다.
	public static final S_ServerMessage sm337_OMAN_5	=	new S_ServerMessage(337, "$2405");// 오만의 탑 5층 이동 주문서가 부족합니다.
	public static final S_ServerMessage sm337_OMAN_6	=	new S_ServerMessage(337, "$2673");// 오만의 탑 6층 이동 주문서가 부족합니다.
	public static final S_ServerMessage sm337_OMAN_7	=	new S_ServerMessage(337, "$2674");// 오만의 탑 7층 이동 주문서가 부족합니다.
	public static final S_ServerMessage sm337_OMAN_8	=	new S_ServerMessage(337, "$2675");// 오만의 탑 8층 이동 주문서가 부족합니다.
	public static final S_ServerMessage sm337_OMAN_9	=	new S_ServerMessage(337, "$2676");// 오만의 탑 9층 이동 주문서가 부족합니다.
	public static final S_ServerMessage sm337_OMAN_10	=	new S_ServerMessage(337, "$2677");// 오만의 탑 10층 이동 주문서가 부족합니다.
	public static final S_ServerMessage sm337_EXPPAPER	=	new S_ServerMessage(337, "$12127");// 구호증서가 부족합니다.
	public static final S_ServerMessage sm337_MANWAL	=	new S_ServerMessage(337, "$10196");// 만월의 정기가 부족합니다.
	public static final S_ServerMessage sm338_MP		=	new S_ServerMessage(338, "$1084");// 당신의%0가 회복되어 갑니다.
	public static final S_ServerMessage sm340			=	new S_ServerMessage(340);// 사용법: 아이템 드래그 후 드롭(1칸)
	public static final S_ServerMessage sm414			=	new S_ServerMessage(414);// 같은 혈맹원이 아닙니다.
	public static final S_ServerMessage sm415			=	new S_ServerMessage(415);// 벌써 다른 파티에 소속해 있기 (위해)때문에 초대할 수 없습니다
	public static final S_ServerMessage sm416			=	new S_ServerMessage(416);// 파티의 리더만을 초대할 수 있습니다.
	public static final S_ServerMessage sm417			=	new S_ServerMessage(417);// 더 이상 파티 멤버를 받아들일 수 없습니다.
	public static final S_ServerMessage sm418			=	new S_ServerMessage(418);// 파티를 해산하였습니다.
	public static final S_ServerMessage sm425			=	new S_ServerMessage(425);// 파티에 가입하고 있지 않습니다.
	public static final S_ServerMessage sm427			=	new S_ServerMessage(427);// 파티의 리더만을 추방할 수 있습니다.
	public static final S_ServerMessage sm428			=	new S_ServerMessage(428);//	편지가 도착했습니다.
	public static final S_ServerMessage sm439			=	new S_ServerMessage(439);// 혈맹: 추방 불가(전쟁중)
	public static final S_ServerMessage sm462			=	new S_ServerMessage(462);// 배가 고파서 채팅을 할 수 없습니다.
	public static final S_ServerMessage sm474			=	new S_ServerMessage(474);// 공성: 선포 불가(성 소유 군주)
	public static final S_ServerMessage sm476			=	new S_ServerMessage(476);// 공성: 공성전은 매 주 일요일 오후 8시부터 가능함
	public static final S_ServerMessage sm478			=	new S_ServerMessage(478);// 공성: 선포 불가(혈맹의 군주만 가능)
	public static final S_ServerMessage sm481			=	new S_ServerMessage(481);// 해당 스탯 최대 값은 45입니다. 다른 스탯을 선택해주세요.
	public static final S_ServerMessage sm489			=	new S_ServerMessage(489);// 물러가려고 하는 애완동물이 너무 많습니다.
	public static final S_ServerMessage sm510			=	new S_ServerMessage(510);// 공지 사항이 전달되는 동안 전체 채팅 및 장사 채팅을 할 수 없습니다.
	public static final S_ServerMessage sm513			=	new S_ServerMessage(513);// 가의 이름이 너무 깁니다.
	public static final S_ServerMessage sm518			=	new S_ServerMessage(518);// 혈맹의 군주만 사용 할 수 있는 기능입니다.
	public static final S_ServerMessage sm519			=	new S_ServerMessage(519);// 아지트: 경매 참여 불가(혈맹 군주가 15레벨 이하)
	public static final S_ServerMessage sm520			=	new S_ServerMessage(520);// 아지트: 이미 성을 소유한 상태
	public static final S_ServerMessage sm521			=	new S_ServerMessage(521);// 아지트: 경매 참여 불가(이미 아지트 소유)
	public static final S_ServerMessage sm522			=	new S_ServerMessage(522);// 아지트: 이미 공선전 참여 상태
	public static final S_ServerMessage sm523			=	new S_ServerMessage(523);// 벌써 다른 집의 경매에 참가하고 있습니다.
	public static final S_ServerMessage sm546			=	new S_ServerMessage(546);// 당신의 파트너는 접속중이지 않습니다.
	public static final S_ServerMessage sm547			=	new S_ServerMessage(547);// 결혼: 배우자가 결혼 반지로는 갈 수 없는 곳에 있음
	public static final S_ServerMessage sm548			=	new S_ServerMessage(548);//	당신의 파트너는 지금게임중입니다.
	public static final S_ServerMessage sm549			=	new S_ServerMessage(549);//	당신의 파트너는 방금로그인했습니다.
	public static final S_ServerMessage sm559			=	new S_ServerMessage(559);// 속죄: 이용 불가(성향 30000 이상 필요)
	public static final S_ServerMessage sm560			=	new S_ServerMessage(560);// 속죄: 이용 불가(PK 횟수 5회 이상 필요)
	public static final S_ServerMessage sm563			=	new S_ServerMessage(563);// 이 곳에서는 사용할 수 없습니다.
	public static final S_ServerMessage sm591			=	new S_ServerMessage(591);// 스크롤이 그렇게 강한 마법을 기록하려면 너무나 약합니다.
	public static final S_ServerMessage sm592			=	new S_ServerMessage(592);// 그 자리에 다른 사람이 서 있으므로 부활시킬 수가 없습니다.
	public static final S_ServerMessage sm623			=	new S_ServerMessage(623);// 아이템 획득 우선권이 없습니다.
	public static final S_ServerMessage sm626			=	new S_ServerMessage(626);// 포탈 이동을 하려면 좀 더 가까워야 합니다.
	public static final S_ServerMessage sm627			=	new S_ServerMessage(627);// 그곳은 이동할 수 있는 곳이 아닙니다.
	public static final S_ServerMessage sm633			=	new S_ServerMessage(633);// 결투: 현재 당신은 결투 상태입니다.
	public static final S_ServerMessage sm634			=	new S_ServerMessage(634);// 결투: 현재 상대는 결투 상태입니다.
	public static final S_ServerMessage sm642			=	new S_ServerMessage(642);// 공성: 성의 주도권 장악
	public static final S_ServerMessage sm643			=	new S_ServerMessage(643);// 공성: 성을 획득함
	public static final S_ServerMessage sm647			=	new S_ServerMessage(647);// 이곳에서는 텔레포트를 할 수 없습니다.
	public static final S_ServerMessage sm652			=	new S_ServerMessage(652);// 결혼: 결혼 상태가 아님
	public static final S_ServerMessage sm657			=	new S_ServerMessage(657);// 결혼: 당신은 이미 결혼한 상태입니다.
	public static final S_ServerMessage sm658			=	new S_ServerMessage(658);// 결혼: 상대가 이미 결혼한 상태입니다.
	public static final S_ServerMessage sm659			=	new S_ServerMessage(659);// 결혼: 당신은 결혼 반지가 없습니다.
	public static final S_ServerMessage sm660			=	new S_ServerMessage(660);// 결혼: 상대가 결혼 반지가 없습니다.
	public static final S_ServerMessage sm661			=	new S_ServerMessage(661);// 결혼: 동성끼리는 결혼 할 수 없습니다.
	public static final S_ServerMessage sm662			=	new S_ServerMessage(662);// 결혼: 결혼 상태가 아님
	public static final S_ServerMessage sm664			=	new S_ServerMessage(664);// 사용법: /교환 (상대와 마주 본 상태)
	public static final S_ServerMessage sm665			=	new S_ServerMessage(665);// 혈맹: 해산 불가(성 또는 아지트 소유중)
	public static final S_ServerMessage sm674			=	new S_ServerMessage(674);// 영혼이 깨끗해지는 것을 느낍니다.
	public static final S_ServerMessage sm676			=	new S_ServerMessage(676);// 기억: 기억창 포화 상태(/파워북 기억확장구슬)
	public static final S_ServerMessage sm678			=	new S_ServerMessage(678);// 정령력을 제거하였습니다.
	public static final S_ServerMessage sm698			=	new S_ServerMessage(698);// 마력에 의해 아무것도 마실 수가 없습니다.
	public static final S_ServerMessage sm728			=	new S_ServerMessage(728);// 창고: 혈맹 창고 이용 불가(수련 계급)
	public static final S_ServerMessage sm739			=	new S_ServerMessage(739);// 경험치 회복: 경험치를 회복할 수 없는 상태
	public static final S_ServerMessage sm743			=	new S_ServerMessage(743);// 소환 불가: 레벨이 맞지 않음
	public static final S_ServerMessage sm755			=	new S_ServerMessage(755);// 교환: 불가(투명 상태)
	public static final S_ServerMessage sm756			=	new S_ServerMessage(756);// 홈타운: 다른 마을에 소속됨
	public static final S_ServerMessage sm757			=	new S_ServerMessage(757);// 홈타운: 10레벨 이상 사용 가능
	public static final S_ServerMessage sm759			=	new S_ServerMessage(759);// 홈타운: 재등록 대기중
	public static final S_ServerMessage sm790			=	new S_ServerMessage(790);// 모두의 축복 중(안)에서, 두 명의 결혼을 했습니다.
	public static final S_ServerMessage sm835			=	new S_ServerMessage(835);// 창고 비밀번호가 일치하지 않습니다.
	public static final S_ServerMessage sm905			=	new S_ServerMessage(905);// 개인 상점: 착용 아이템 판매 불가
	public static final S_ServerMessage sm906			=	new S_ServerMessage(906);// 개인 상점: 판매 아이템과 소지 아이템이 일치하지 않음
	public static final S_ServerMessage sm908			=	new S_ServerMessage(908);// 개인 상점: 등록 아이템 없음
	public static final S_ServerMessage sm912			=	new S_ServerMessage(912);// 채팅을 할 수 없습니다.
	public static final S_ServerMessage sm939			=	new S_ServerMessage(939);// 지금은 사용할 수 없는 상태입니다.
	public static final S_ServerMessage sm941			=	new S_ServerMessage(941);// 거래 불가 아이템입니다.
	public static final S_ServerMessage sm942			=	new S_ServerMessage(942);// 상대의 아이템이 너무 무겁기 (위해)때문에, 더 이상 줄 수 없습니다.
	public static final S_ServerMessage sm990			=	new S_ServerMessage(990);// 공성: 성문 자동 수리 명령을 내림
	public static final S_ServerMessage sm991			=	new S_ServerMessage(991);// 공성: 성문 자동 수리 명령을 취소함
	public static final S_ServerMessage sm1003			=	new S_ServerMessage(1003);// 투명 상태에서 사용할 수 없는 마법입니다.
	public static final S_ServerMessage sm1007			=	new S_ServerMessage(1007);// MP 회복 속도가 빨라집니다.
	public static final S_ServerMessage sm1019			=	new S_ServerMessage(1019);// 신고: 접수 완료
	public static final S_ServerMessage sm1020			=	new S_ServerMessage(1020);// 신고: 이미 신고 된 대상
	public static final S_ServerMessage sm1021			=	new S_ServerMessage(1021);// 잠시후 다시 신고 해주세요.
	public static final S_ServerMessage sm1064			=	new S_ServerMessage(1064);// 혈맹에 소속되어 있지 않습니다.(/파워북 혈맹매칭)
	public static final S_ServerMessage sm1078			=	new S_ServerMessage(1078);// 발록의 웃음소리가 뇌리를 강타합니다.
	public static final S_ServerMessage sm1079			=	new S_ServerMessage(1079);// 야히의 모습이 점점 친근하게 느껴집니다.
	public static final S_ServerMessage sm1080			=	new S_ServerMessage(1080);// 발록의 냉소가 느껴져 오한이 듭니다.
	public static final S_ServerMessage sm1081			=	new S_ServerMessage(1081);// 야히의 모습을 기억하기가 어려워집니다.
	public static final S_ServerMessage sm1098			=	new S_ServerMessage(1098);// 아지트: 지하 아지트 없음
	public static final S_ServerMessage sm1099			=	new S_ServerMessage(1099);// 아지트: 지하 아지트 생성 완료
	public static final S_ServerMessage sm1127			=	new S_ServerMessage(1127);// 권한 부여: 거대한 마족 공격 가능
	public static final S_ServerMessage sm1135			=	new S_ServerMessage(1135);// 아지트: 이미 지하 아지트 소유중
	public static final S_ServerMessage sm1136			=	new S_ServerMessage(1136);// 낚시: 물고기를 놓침
	public static final S_ServerMessage sm1137			=	new S_ServerMessage(1137);// 낚시: 미끼 부족
	public static final S_ServerMessage sm1138			=	new S_ServerMessage(1138);// 여기에 낚싯대를 던질 수 없습니다.
	public static final S_ServerMessage sm1140			=	new S_ServerMessage(1140);// 권한 부여: 저주받은 무녀 사엘 공격 가능
	public static final S_ServerMessage sm1141			=	new S_ServerMessage(1141);// 권한 부여: 원한에 찬 유령 공격 가능
	public static final S_ServerMessage sm1142			=	new S_ServerMessage(1142);// 권한 부여: 원한에 찬 하멜장군 공격 가능
	public static final S_ServerMessage sm1143			=	new S_ServerMessage(1143);// 마법 인형: 인형에 따라 고유의 능력 부여
	public static final S_ServerMessage sm1161			=	new S_ServerMessage(1161);// 용해할 수 없습니다.
	public static final S_ServerMessage sm1162			=	new S_ServerMessage(1162);// 벌써 주위에 모닥불이 있습니다.
	public static final S_ServerMessage sm1163			=	new S_ServerMessage(1163);// 낚시가 종료했습니다.
	public static final S_ServerMessage sm1170			=	new S_ServerMessage(1170);// 이곳에서 변신할수 없습니다.
	public static final S_ServerMessage sm1182			=	new S_ServerMessage(1182);// 이미 게임이 진행 되었네.
	public static final S_ServerMessage sm1183			=	new S_ServerMessage(1183);// 지금은 유령의 집을 청소 중이라네.
	public static final S_ServerMessage sm1184			=	new S_ServerMessage(1184);// 이미 유령의 집이 포화 상태라네.
	public static final S_ServerMessage sm1187			=	new S_ServerMessage(1187);// 펫: 해당 펫 목걸이 사용중
	public static final S_ServerMessage sm1198			=	new S_ServerMessage(1198);// 동맹: 상대가 신청을 거절함
	public static final S_ServerMessage sm1199			=	new S_ServerMessage(1199);// 동맹: 신청 불가(비연합 혈맹의 25레벨 이상 군주가 아님)
	public static final S_ServerMessage sm1201			=	new S_ServerMessage(1201);// 동맹에 가입할 수 없습니다.
	public static final S_ServerMessage sm1202			=	new S_ServerMessage(1202);// 이미 동맹에 가입된 상태입니다.
	public static final S_ServerMessage sm1203			=	new S_ServerMessage(1203);// 전쟁중에는 동맹을 탈퇴할 수 없습니다.
	public static final S_ServerMessage sm1205			=	new S_ServerMessage(1205);// 동맹: 전쟁 선포 불가(동맹 결성 혈맹)
	public static final S_ServerMessage sm1206			=	new S_ServerMessage(1206);// 25레벨이상 혈맹 군주만 동맹신청을 할 수 있습니다. 또한 연합 군주는 동맹을 맺을 수 없습니다.
	public static final S_ServerMessage sm1233			=	new S_ServerMessage(1233);// 동맹이 없습니다.
	public static final S_ServerMessage sm1234			=	new S_ServerMessage(1234);// 전쟁중에는 동맹에 가입할 수 없습니다.
	public static final S_ServerMessage sm1235			=	new S_ServerMessage(1235);// 동맹이 있는 경우 혈맹을 해산할 수 없습니다.
	public static final S_ServerMessage sm1240			=	new S_ServerMessage(1240);// 편지: 보내기 불가(상대방 편지함 포화 상태)
	public static final S_ServerMessage sm1259			=	new S_ServerMessage(1259);// 잠시 후 마을로 이동됩니다.
	public static final S_ServerMessage sm1290			=	new S_ServerMessage(1290);// 회상의 촛불이 있어야 스탯 초기화가 가능합니다.
	public static final S_ServerMessage sm1294			=	new S_ServerMessage(1294);// 인챈트: 해당 강화 주문서 사용 불가
	public static final S_ServerMessage sm1301			=	new S_ServerMessage(1301);// 소환된 펫이 없습니다.
	public static final S_ServerMessage sm1310			=	new S_ServerMessage(1310);// 인챈트: 강렬하게 빛났지만 아무 일도 없었습니다.
	public static final S_ServerMessage sm1313			=	new S_ServerMessage(1313);// 성장의 축복: EXP+20%
	public static final S_ServerMessage sm1348			=	new S_ServerMessage(1348);// 큐브-리치: SP+2
	public static final S_ServerMessage sm1413			=	new S_ServerMessage(1413);// 현재 상태에서는 사용할 수 없습니다.
	public static final S_ServerMessage sm1426			=	new S_ServerMessage(1426);// 도감 1단계 달성: EXP+20% 대미지 감소+5
	public static final S_ServerMessage sm1453			=	new S_ServerMessage(1453);// 더 이상 장비를 강화할 수 없습니다.
	public static final S_ServerMessage sm1518			=	new S_ServerMessage(1518);// 낚시중단 무게 게이지 부족
	public static final S_ServerMessage sm1536			=	new S_ServerMessage(1536);// 인원이 가득차서 더 이상 입장할 수 없습니다.
	public static final S_ServerMessage sm1537			=	new S_ServerMessage(1537);// 드래곤이 깨서 진입 못한다
	public static final S_ServerMessage sm1626			=	new S_ServerMessage(1626);// 드래곤 버프로인해 입장이 불가능합니다.
	public static final S_ServerMessage sm1655			=	new S_ServerMessage(1655);// 같은 기억명으로 저장할 수 없습니다.
	public static final S_ServerMessage sm1695			=	new S_ServerMessage(1695);// 파티장을 위임시킬 동료가 근처에 없습니다
	public static final S_ServerMessage sm1696			=	new S_ServerMessage(1696);// 현재 파티에 있는 구성원이 아닙니다
	public static final S_ServerMessage sm1697			=	new S_ServerMessage(1697);// 파티장이 아니어서 권한을 행사할 수 없습니다
	public static final S_ServerMessage sm1729			=	new S_ServerMessage(1729);// 아직은 사용할 수 없습니다.
	public static final S_ServerMessage sm1782			=	new S_ServerMessage(1782);
	public static final S_ServerMessage sm1785			=	new S_ServerMessage(1785);
	public static final S_ServerMessage sm1823			=	new S_ServerMessage(1823);// 약속했던 시간이되어 새로운 아이템이 생겼습니다. 인벤토리를 확인해주세요.
	public static final S_ServerMessage sm1891			=	new S_ServerMessage(1891);// 드래곤의 숨결이 깃든 땅에서만 사용할 수 있습니다.
	public static final S_ServerMessage sm1892			=	new S_ServerMessage(1892);// 사용불가 지역
	public static final S_ServerMessage sm1973			=	new S_ServerMessage(1973);// 생존의 외침: 무기 착용 필요
	public static final S_ServerMessage sm1974			=	new S_ServerMessage(1974);// 생존의 외침: 대기중
	public static final S_ServerMessage sm2071			=	new S_ServerMessage(2071);// 계급: 수호 기사는 5명까지 임명 가능
	public static final S_ServerMessage sm2116			=	new S_ServerMessage(2116);// 성장의 축복: EXP+40%
	public static final S_ServerMessage sm2117			=	new S_ServerMessage(2117);// 성장의 축복: EXP+30%
	public static final S_ServerMessage sm2140			=	new S_ServerMessage(2140);// 아인하사드의 축복: 지수 충전, EXP+77%(드래곤의 보석류 사용 불가)
	public static final S_ServerMessage sm2142			=	new S_ServerMessage(2142);// 아인하사드의 축복: 지수 충전(드래곤의 에메랄드 사용 불가)
	public static final S_ServerMessage sm2145			=	new S_ServerMessage(2145);// 아인하사드의 축복: 지수 충전(드래곤의 에메랄드 사용 불가)
	public static final S_ServerMessage sm2146			=	new S_ServerMessage(2146);// 아인하사드의 축복: 드래곤의 보석류 사용 불가
	public static final S_ServerMessage sm2147			=	new S_ServerMessage(2147);// 아인하사드의 축복: 드래곤의 에메랄드, 자수정 중복 사용 불가
	public static final S_ServerMessage sm2887			=	new S_ServerMessage(2887);// 특정 아이템이 있어 아직은 사용할 수 없습니다.
	public static final S_ServerMessage sm2920			=	new S_ServerMessage(2920);// 기억 저장 구슬: 기억 장소 목록 저장 완료
	public static final S_ServerMessage sm2921			=	new S_ServerMessage(2921);// 어딘가에 드래곤포탈이 열렷습니다
	public static final S_ServerMessage sm2930			=	new S_ServerMessage(2930);// 기억: 기억창은 최대 100개까지 확장 가능
	public static final S_ServerMessage sm2963			=	new S_ServerMessage(2963);// 기억 저장 구슬: 저장 불가(기억 장소 목록이 없음)
	public static final S_ServerMessage sm3073			=	new S_ServerMessage(3073);// 큐브-아바타: 모든 공격력+10, 맞는 대미지+5% 증가
	public static final S_ServerMessage sm3074			=	new S_ServerMessage(3074);// 큐브-오우거: 근거리 대미지+4, 근거리 명중+4
	public static final S_ServerMessage sm3075			=	new S_ServerMessage(3075);// 큐브-골렘:AC-8
	public static final S_ServerMessage sm3082			=	new S_ServerMessage(3082);// 차단되어 편지를 보낼 수 없습니다.
	public static final S_ServerMessage sm3237			=	new S_ServerMessage(3237);// 이미 학습을 한 상태입니다.
	public static final S_ServerMessage sm3245			=	new S_ServerMessage(3245);// 군주의 부름: 혈맹에 가입하세요
	public static final S_ServerMessage sm3246			=	new S_ServerMessage(3246);// 군주의 부름: 혈원을 모집하세요
	public static final S_ServerMessage sm3247			=	new S_ServerMessage(3247);// 혈맹을 창설하고 쉽게 알리세요
	public static final S_ServerMessage sm3253			=	new S_ServerMessage(3253);// 슬롯 확장: 착용 불가(레벨이 부족함)
	public static final S_ServerMessage sm3278			=	new S_ServerMessage(3278);// 슬롯 확장: 같은 종류 추가 착용 불가
	public static final S_ServerMessage sm3279			=	new S_ServerMessage(3279);// 슬롯 확장: 해당 아이템 추가 착용 불가
	public static final S_ServerMessage sm3319			=	new S_ServerMessage(3319);// 동일한 속성에는 사용하실 수없습니다.
	public static final S_ServerMessage sm3324			=	new S_ServerMessage(3324);// 혈맹 주시: 문장 주시 불가, 대상 혈맹과 전쟁 상태
	public static final S_ServerMessage sm3349			=	new S_ServerMessage(3349);// 혈맹 주시: 문장 주시 불가, 없는 혈맹 혹은 연합혈맹 이거나 군주가 오프라인 상태
	public static final S_ServerMessage sm3361			=	new S_ServerMessage(3361);// 혈맹 주시: 상대 혈맹의 이름을 입력하세요.
	public static final S_ServerMessage sm3362			=	new S_ServerMessage(3362);// 클라이언트의 버전이 낮습니다. 리니지를 재시작 해주세요.
	public static final S_ServerMessage sm3383			=	new S_ServerMessage(3383);// 혈맹 주시: 전쟁 상태에선 사용 불가
	public static final S_ServerMessage sm3405			=	new S_ServerMessage(3405);// 상점 개설이 불가능한 곳입니다. 바닥을 확인해 주세요.
	public static final S_ServerMessage sm3413			=	new S_ServerMessage(3413);// 드래곤키를 소유하고잇어 구입이 불가능합니다
	public static final S_ServerMessage sm3416			=	new S_ServerMessage(3416);// 드래곤의 저주로 인해 구입할 수 없습니다
	public static final S_ServerMessage sm3417			=	new S_ServerMessage(3417);// 드래곤키가 모두 판매되어 구입이 불가능합니다
	public static final S_ServerMessage sm3457			=	new S_ServerMessage(3457);// 더 이상 쾌속 릴을 사용할 수 없습니다.
	public static final S_ServerMessage sm3461			=	new S_ServerMessage(3461);// 포만감이 부족하여 사용할 수 없습니다.
	public static final S_ServerMessage sm3556			=	new S_ServerMessage(3556);// 아이템 제작에 성공했습니다.
	public static final S_ServerMessage sm3557			=	new S_ServerMessage(3557);// 아이템 제작에 실패했습니다.
	public static final S_ServerMessage sm3558			=	new S_ServerMessage(3558);// 재료 아이템이 잘못되었습니다.
	public static final S_ServerMessage sm3559			=	new S_ServerMessage(3559);// 아데나가 부족합니다.
	public static final S_ServerMessage sm3560			=	new S_ServerMessage(3560);// 인벤토리 공간이 부족합니다.
	public static final S_ServerMessage sm3561			=	new S_ServerMessage(3561);// 무게 게이지가 가득 찼습니다.
	public static final S_ServerMessage sm3564			=	new S_ServerMessage(3564);// 잘못된 제작 요청입니다.
	public static final S_ServerMessage sm3567			=	new S_ServerMessage(3567);// 제작 재료 아이템이 부족합니다.
	public static final S_ServerMessage sm3569			=	new S_ServerMessage(3569);// 제작 NPC가 범위 밖에 있습니다.
	public static final S_ServerMessage sm3570			=	new S_ServerMessage(3570);// 제작에 실패했습니다.
	public static final S_ServerMessage sm3572			=	new S_ServerMessage(3572);// N코인 보유량을 확인 중입니다. 잠시만 기다려 주시기 바랍니다.
	public static final S_ServerMessage sm3575			=	new S_ServerMessage(3575);// 제작 NPC가 너무 멀리 있습니다.
	public static final S_ServerMessage sm3591			=	new S_ServerMessage(3591);// 계급: 정예 계급은 15명까지 임명 가능
	public static final S_ServerMessage sm3680			=	new S_ServerMessage(3680);// 투석기 사용: 실패(재장전 시간 필요)
	public static final S_ServerMessage sm3681			=	new S_ServerMessage(3681);// 투석기 사용: 실패(전쟁을 선포한 군주만 사용 가능)
	public static final S_ServerMessage sm3682			=	new S_ServerMessage(3682);// 투석기 사용: 실패(성을 수호하는 성혈 군주만 사용 가능)
	public static final S_ServerMessage sm3683			=	new S_ServerMessage(3683);// 투석기 사용: 실패(공성 시간에만 사용 가능)
	public static final S_ServerMessage sm3798			=	new S_ServerMessage(3798);// 경험치 손실이 없는 지역 : 경험치가 손실되지 않았습니다.
	public static final S_ServerMessage sm3805			=	new S_ServerMessage(3805);// 사망 패널티가 없는 지역: 패널티를 입지 않앗습니다.
	public static final S_ServerMessage sm3845			=	new S_ServerMessage(3845);// 마법 사용에 필요한 장비를 착용하지 않아 사용이 불가능합니다.
	public static final S_ServerMessage sm3904			=	new S_ServerMessage(3904);// 성장의 고리는 최대 5캐릭터에게 적용할 수 있습니다.
	public static final S_ServerMessage sm3916			=	new S_ServerMessage(3916);// 성장의 고리가 연결 되었습니다.
	public static final S_ServerMessage sm3917			=	new S_ServerMessage(3917);// 성장의 고리 사용이 예약되었습니다.
	public static final S_ServerMessage sm3980			=	new S_ServerMessage(3980);// 혈맹 가입 종류가 정상적으로 변경되었습니다.
	public static final S_ServerMessage sm3992			=	new S_ServerMessage(3992);// 토마호크: 출혈 상태
	public static final S_ServerMessage sm4472			=	new S_ServerMessage(4472);// 현재 레벨에서 복용할 수 있는 엘릭서의 수량을 모두 사용했습니다.
	public static final S_ServerMessage sm4473			=	new S_ServerMessage(4473);// 더 이상 엘릭서를 복용할 수 없습니다.
	public static final S_ServerMessage sm4487			=	new S_ServerMessage(4487);// PC방 전용 콘텐츠 입니다.
	public static final S_ServerMessage sm4524			=	new S_ServerMessage(4524);// 잠시 후에 다시 시도해 주세요.
	public static final S_ServerMessage sm4608			=	new S_ServerMessage(4608);// 안전한 곳에서 실행해주세요.
	public static final S_ServerMessage sm4615			=	new S_ServerMessage(4615);// 해당 버프가 이미 활성화 되어 있습니다.
	public static final S_ServerMessage sm4684			=	new S_ServerMessage(4684);// 아지트 통로가 열렸습니다. 랭킹 카운트가 시작 됩니다.
	public static final S_ServerMessage sm4726			=	new S_ServerMessage(4726);// 몬스터 도감: 해당 지역에서는 작동 하지 않습니다.
	public static final S_ServerMessage sm4734			=	new S_ServerMessage(4734);// 그레이스: 모든 내성 상승
	public static final S_ServerMessage sm4737			=	new S_ServerMessage(4737);// 데스힐: 치유 마법의 회복량을 대미지로 받음
	public static final S_ServerMessage sm4741			=	new S_ServerMessage(4741);// 그레이스 종료
	public static final S_ServerMessage sm4761			=	new S_ServerMessage(4761);// 임팩트: 기술,공포,정령,용언 적중 상승
	public static final S_ServerMessage sm4923			=	new S_ServerMessage(4923);// 모든 인원이 준비되었습니다. 1분 이내에 시작하지 않으면 방에서 퇴장하게 됩니다.
	public static final S_ServerMessage sm5011			=	new S_ServerMessage(5011);// 할파스의 저주 버프
	public static final S_ServerMessage sm5077			=	new S_ServerMessage(5077);// [견갑] 슬롯을 개방한 후 착용할 수 있습니다.
	public static final S_ServerMessage sm5078			=	new S_ServerMessage(5078);// [휘장] 슬롯을 개방한 후 착용할 수 있습니다.
	public static final S_ServerMessage sm5276			=	new S_ServerMessage(5276);// 지금은 펫을 소환할 수 업습니다.
	public static final S_ServerMessage sm5277			=	new S_ServerMessage(5277);// 지금은 부활할 수 없습니다
	public static final S_ServerMessage sm5308			=	new S_ServerMessage(5308);// 선행되는 스킬을 배우지 않았습니다.
	public static final S_ServerMessage sm5317			=	new S_ServerMessage(5317);// 우정 포인트가 부족하여 강화할 수 업습니다.
	public static final S_ServerMessage sm5318			=	new S_ServerMessage(5318);// 강화촉매제가 부족하여 강화할 수 없습니다.
	public static final S_ServerMessage sm5359			=	new S_ServerMessage(5359);// 입장에 필요한 조건이 맞지 않습니다.
	public static final S_ServerMessage sm5377			=	new S_ServerMessage(5377);// 지배의 탑에서만 사용이 가능합니다.
	public static final S_ServerMessage sm6648			=	new S_ServerMessage(6648);// 밤시간 동안 무작위 텔레포트를 할 수 없는 지역입니다.
	public static final S_ServerMessage sm6871			=	new S_ServerMessage(6871);// [PSS 종료] 플레이 서포트가 종료되었어요. 캐릭터 상태를 확인해보세요.
	public static final S_ServerMessage sm7030			=	new S_ServerMessage(7030);// 아인하사드의 가호 효과를 이미 받고 있습니다.
	public static final S_ServerMessage sm7052			=	new S_ServerMessage(7052);// 창에 꿰뚫려 행동에 제약을 받습니다.
	public static final S_ServerMessage sm7054			=	new S_ServerMessage(7054);// 군주의 외침이 믿을 수 없는 용기를 부여합니다.
	public static final S_ServerMessage sm7091			=	new S_ServerMessage(7091);// 혈맹이 없는 상태에서 해당 마법은 사용할 수 없습니다.
	public static final S_ServerMessage sm7437			=	new S_ServerMessage(7437);// 할파스의 신의: 재 사용 대기중
	public static final S_ServerMessage sm7465			=	new S_ServerMessage(7465);// 할파스의 신의: 죽음의 위기에서 HP 전부 회복, 자동 발동 대기중
	public static final S_ServerMessage sm7492			=	new S_ServerMessage(7492);// ** 희망의 불꽃을 획득하였습니다. 게렝에게 시공의 막대를 지급받으세요 **
	public static final S_ServerMessage sm7510			=	new S_ServerMessage(7510);// ** 인벤토리에 지급받은 화염의 상자를 확인하세요 **
	public static final S_ServerMessage sm7511			=	new S_ServerMessage(7511);// ** 인벤토리에 지급받은 혹한의 상자를 확인하세요 **
	public static final S_ServerMessage sm7512			=	new S_ServerMessage(7512);// ** 인벤토리에 지급받은 섬광의 상자를 확인하세요 **
	public static final S_ServerMessage sm7552			=	new S_ServerMessage(7552);// 아인하사드 포인트를 더 이상  얻을 수 없습니다.
	public static final S_ServerMessage sm7577			=	new S_ServerMessage(7577);// 충전불가: 충전 제한 횟수 소진
	public static final S_ServerMessage sm7619			=	new S_ServerMessage(7619);// 드래곤 포탈: 입장 불가
	public static final S_ServerMessage sm7620			=	new S_ServerMessage(7620);// 할파스의 은신처: 입장 불가
	public static final S_ServerMessage sm7624			=	new S_ServerMessage(7624);// 현재 이 제작은 사용하실 수 없습니다.
	public static final S_ServerMessage sm7635			=	new S_ServerMessage(7635);// 해당 지역은 이동 불가한 위치입니다.
	public static final S_ServerMessage sm7802			=	new S_ServerMessage(7802);// 아인하사드의 가호가 예약 되었습니다.
	public static final S_ServerMessage sm7803			=	new S_ServerMessage(7803);// 아인하사드의 가호 예약이 취소되었습니다.
	public static final S_ServerMessage sm7804			=	new S_ServerMessage(7804);// 이미 예약되어 추가 예약은 불가능 합니다.
	public static final S_ServerMessage sm7855			=	new S_ServerMessage(7855);// 레벨이 부족하여 슬롯을 개방할 수 없습니다.
	public static final S_ServerMessage sm7856			=	new S_ServerMessage(7856);// 이미 존재하는 이름 입니다. 다시 변경 부탁드립니다.
	public static final S_ServerMessage sm7921			=	new S_ServerMessage(7921);// 계급: 부군주는 1명까지 임명 가능
	public static final S_ServerMessage sm7922			=	new S_ServerMessage(7922);// 계급: 일반 계급은 28명까지 임명 가능
	public static final S_ServerMessage sm7944			=	new S_ServerMessage(7944);// 소개 내용이 너무 깁니다. (최대 40 bytes)
	public static final S_ServerMessage sm7974			=	new S_ServerMessage(7974);// 혈맹 성장 버프1: EXP+10
	public static final S_ServerMessage sm7975			=	new S_ServerMessage(7975);// 혈맹 성장 버프2: EXP+30
	public static final S_ServerMessage sm7976			=	new S_ServerMessage(7976);// 혈맹 전투 버프1: HP+50, 명중+1, 추가 대미지+1, MR+3
	public static final S_ServerMessage sm7977			=	new S_ServerMessage(7977);// 혈맹 전투 버프2: HP+100, 명중+2, 추가 대미지+2, MR+5, 모든 적중+1
	public static final S_ServerMessage sm7980			=	new S_ServerMessage(7980);// 지금은 이용할 수 없습니다.
	public static final S_ServerMessage sm7985			=	new S_ServerMessage(7985);// 슬롯 개방이 불가능한 지역입니다. 안전한 장소에서 다시 시도해주세요.
	public static final S_ServerMessage sm7986			=	new S_ServerMessage(7986);// 너무 멀리 떨어져 있습니다.
	public static final S_ServerMessage sm7996			=	new S_ServerMessage(7996);// 공지 내용이 너무 깁니다. (최대 270 bytes)
	public static final S_ServerMessage sm8322			=	new S_ServerMessage(8322);// 인터서버에서는 이용할 수 없습니다.
	public static final S_ServerMessage sm8332			=	new S_ServerMessage(8332);// 로우풀 상태에서는 입장이 불가능합니다.
	public static final S_ServerMessage sm8333			=	new S_ServerMessage(8333);// 뉴트럴 상태에서는 입장이 불가능합니다.
	public static final S_ServerMessage sm8334			=	new S_ServerMessage(8334);// 카오틱 상태에서는 입장이 불가능합니다.
	public static final S_ServerMessage sm8415			=	new S_ServerMessage(8415);// 소환된 몬스터가 없습니다.
	public static final S_ServerMessage sm8584			=	new S_ServerMessage(8584);// 보물을 발굴할 수 있는 장소가 아닙니다.
	public static final S_ServerMessage sm8587			=	new S_ServerMessage(8587);// 클라이언트를 업데이트해주세요.
	public static final S_ServerMessage sm8598			=	new S_ServerMessage(8598);// 입장 불가 : 입장 불가 아이템 소지
	public static final S_ServerMessage sm8605			=	new S_ServerMessage(8605);// 전장을 벗어나 있을 경우, 시간이 경과할 때마다 보유한 훈장이 1개씩 감소합니다.
	public static final S_ServerMessage sm8702			=	new S_ServerMessage(8702);// 엘릭서 추출에 성공하였습니다.
	public static final S_ServerMessage sm8703			=	new S_ServerMessage(8703);// 엘릭서 추출에 실패하였습니다.
	public static final S_ServerMessage sm8712			=	new S_ServerMessage(8712);// 불멸의 가호(이벤트 가호) 류를 소지하고 있지 않아 부활할 수 없습니다.
	public static final S_ServerMessage sm8735			=	new S_ServerMessage(8735);// 혈맹 창고에 아이템이 존재합니다.
	public static final S_ServerMessage sm8955			=	new S_ServerMessage(8955);// 혈맹 방어 버프1: AC-1, 대미지 리덕션+1, MR+5%
	public static final S_ServerMessage sm8956			=	new S_ServerMessage(8956);// 혈맹 방어 버프1: AC-2, 대미지 리덕션+2, MR+10%, 모든 내성+1
	public static final S_ServerMessage sm8957			=	new S_ServerMessage(8957);// 혈맹 방어 버프가 사라집니다.
	public static final S_ServerMessage sm9018			=	new S_ServerMessage(9018);// 전시회 기간을 늘리거나 전시했던 장비 중 일부를 무료로 재등록합니다.
	public static final S_ServerMessage sm9023			=	new S_ServerMessage(9023);// 선택한 장비를 전시 등록할 수 없습니다.
	public static final S_ServerMessage sm9075			=	new S_ServerMessage(9075);// 제련석을 장착할 수 없는 아이템입니다.
	public static final S_ServerMessage sm9076			=	new S_ServerMessage(9076);// 제련 슬롯이 존재하지 않습니다.
	public static final S_ServerMessage sm9077			=	new S_ServerMessage(9077);// 제련석 추출에 실패하였습니다.
	public static final S_ServerMessage sm9078			=	new S_ServerMessage(9078);// 제련석 추출에 성공하였습니다.
	public static final S_ServerMessage sm9079			=	new S_ServerMessage(9079);// 제련석 장착에 성공하였습니다.
	public static final S_ServerMessage sm9082			=	new S_ServerMessage(9082);// 제련석이 장착된 상태에서는 아이템 강화를 할 수 없습니다.
	public static final S_ServerMessage sm9159			=	new S_ServerMessage(9159);// 해당 슬롯에 이미 제련석이 존재합니다.
	public static final S_ServerMessage sm9160			=	new S_ServerMessage(9160);// 추출할 제련석이 존재하지 않습니다.
	public static final S_ServerMessage sm9165			=	new S_ServerMessage(9165);// 제련석이 사라졌습니다.
	public static final S_ServerMessage sm9166			=	new S_ServerMessage(9166);// 동일한 제련석이 이미 존재합니다.
	public static final S_ServerMessage sm9167			=	new S_ServerMessage(9167);// 삽입할 제련석 슬롯이 유효하지 않습니다.
	public static final S_ServerMessage sm9171			=	new S_ServerMessage(9171);// 해당 제련석을 등록할 수 없습니다.
	public static final S_ServerMessage sm9191			=	new S_ServerMessage(9191);// 현재 위치에서는 제련석을 합성할 수 없습니다.
	public static final S_ServerMessage sm9241			=	new S_ServerMessage(9241);// 픽시의 축복으로 죽음을 극복합니다. 사망 경험치와 아이템 드랍 패널티가 없습니다.
	public static final S_ServerMessage sm9246			=	new S_ServerMessage(9246);// 기간제 아이템에는 제련석을 사용이 불가능 합니다.
	public static final S_ServerMessage sm9247			=	new S_ServerMessage(9247);// 제련석 교체에 필요한 재료의 수량이 부족합니다.
	public static final S_ServerMessage sm9274			=	new S_ServerMessage(9274);// 순서가 올바르지 않아 제련석 추출에 실패하였습니다.
	public static final S_ServerMessage sm9310			=	new S_ServerMessage(9310);// 아인하사드 포인트가 부족합니다.
	public static final S_ServerMessage sm9607			=	new S_ServerMessage(9607);// 혈맹 군주 위임에 실패하였습니다.
}

