package l1j.server.server; 

public class Opcodes_201028 {
	
	// client code
	public static final int C_MERCENARYNAME				= 0x01;
	public static final int C_ACTION					= 0x03;	// <알트+1 ~ 5 까지 액션 >
	public static final int C_PLATE						= 0x05;
	public static final int C_CONTROL_WEATHER			= 0x08;
	public static final int C_ADD_XCHG					= 0x09;	// 교환창에 아이템 추가
	public static final int C_RETURN_SUMMON				= 0x0a;	// 텔레포트 사용
	public static final int C_FAR_ATTACK				= 0x0d;	// 활공격 부분
	public static final int C_MERCENARYSELECT			= 0x0F;
	public static final int C_CHANNEL					= 0x10;	// 불량 유저 신고(신고)
	public static final int C_INVITE_PARTY				= 0x11;	// 찾음[본섭] (현재 미사용 )
	public static final int C_ATTACK					= 0x12;	// 일반공격 부분
	public static final int C_BANISH_PARTY				= 0x14;	// 파티 추방 (현재 미사용 )
	public static final int C_BUILDER_CONTROL			= 0x17;	
	public static final int C_READ_NOTICE				= 0x19;	// 로그인 후 패킷
	public static final int C_REGISTER_QUIZ				= 0x1a;
	public static final int C_BAN						= 0x1c;
	public static final int C_LEAVE_PLEDGE				= 0x1d;	// 혈맹 탈퇴
	public static final int C_SILENCE					= 0x1f;
	public static final int C_CREATE_CUSTOM_CHARACTER	= 0x21;	// 케릭 생성
	public static final int C_SHUTDOWN					= 0x23;	// 혈맹창 공지, 메모
	public static final int C_EXTENDED_HYBRID			= 0x24;	// 찾음[본섭] (현재 미사용 )
	public static final int C_QUERY_CASTLE_SECURITY		= 0x25;	// 성내 치안관리
	public static final int C_SELECT_TIME				= 0x26;
	public static final int C_BAN_MEMBER				= 0x28;	// 혈맹 추방 명령어
	public static final int C_TAX						= 0x29;	// 세금 조정
	public static final int C_DELETE_BOOKMARK			= 0x2a;	// [기억 후 기억목록클릭 delete]
	public static final int C_ARCHERARRANGE				= 0x2b;
	public static final int C_MERCENARYARRANGE			= 0x2E;
	public static final int C_EXCHANGE_SPELL			= 0x30;	// horunOK
	public static final int C_LOGIN_TEST				= 0x31;
	public static final int C_FIX						= 0x32;	// 무기수리, 펫인출
	public static final int C_TELL						= 0x34;
	public static final int C_MAIL						= 0x35;	// 편지 읽기
	public static final int C_WANTED					= 0x36;
	public static final int C_CREATE_PLEDGE				= 0x39;
	public static final int C_GOTO_MAP					= 0x3b;
	public static final int C_TELEPORT_USER				= 0x3c;
	public static final int C_EXCHANGEABLE_SPELL		= 0x3e;	// horun
	public static final int C_BOARD_READ				= 0x3F;	// 게시판 읽기 (현재 미사용 )
	public static final int C_ALIVE						= 0x40;	// 1분마다 한번씩 옴
	public static final int C_TELEPORT					= 0x41;
	public static final int C_ATTACK_CONTINUE			= 0x42;	// 자동칼질
	public static final int C_EXCLUDE					= 0x45;
	public static final int C_WHO						= 0x46;	// [누구]
	public static final int C_LOGIN_RESULT				= 0x47;
	public static final int C_PLEDGE_WATCH				= 0x48;	// 문장 주시 혈맹 목록
	public static final int C_WAREHOUSE_CONTROL			= 0x49;	// 창고 비번.
	public static final int C_CHECK_PK					= 0x4b;	// [checkpk]
	public static final int C_ANSWER					= 0x4c;	// [ Y , N ] 선택 부분
	public static final int C_FIXABLE_ITEM				= 0x4d;	// 무기수리리스트
	public static final int C_VERSION					= 0x4e;
	public static final int C_UPLOAD_EMBLEM				= 0x4f;	// 문장데이타를 서버에 요청함
	public static final int C_RESTART					= 0x50;	// 겜중에 리스창으로 빠짐. [ C_CHARACTERCONFIG 다음에 날라옴 ]
	public static final int C_CHAT_PARTY_CONTROL		= 0x51;	// 채팅파티채팅초대 (현재 미사용 )
	public static final int C_DESTROY_ITEM				= 0x52;	// 휴지통에 아이템 삭제
	public static final int C_CHAT						= 0x54;
	public static final int C_CHECK_INVENTORY			= 0x55;
	public static final int C_DROP						= 0x57;	// 아이템 떨구기
	public static final int C_ALT_ATTACK				= 0x5c;
	public static final int C_ENTER_PORTAL				= 0x5d;	// (ENTER_PORTAL)
	public static final int C_BOOK						= 0x5e;	// 찾음[본섭]  (현재 미사용 )
	public static final int C_WHO_PARTY					= 0x5F;
	public static final int C_LOGIN						= 0x62;	// v 계정정보가 담긴 패킷(클라이언트 로그인 방식)
	public static final int C_JOIN_PLEDGE				= 0x63;
	public static final int C_GIVE						= 0x65;	// 강제로 아이템 주기
	public static final int C_INVITE_PARTY_TARGET		= 0x67;	// 파티 초대 (현재 미사용 )
	public static final int C_BOOKMARK					= 0x68;	// [기억 OO]
	public static final int C_MERCENARYEMPLOY			= 0x69;	// 용병구매
	public static final int C_SAY						= 0x6B;
	public static final int C_MARRIAGE					= 0x6d;	// [청혼]
	public static final int C_BOARD_WRITE				= 0x6F;
	public static final int C_KICK						= 0x70;
	public static final int C_NEW_ACCOUNT				= 0x71;
	public static final int C_ADDR						= 0x72;
	public static final int C_PERSONAL_SHOP				= 0x73;	// 개인상점 (현재 미사용)
	public static final int C_RANK_CONTROL				= 0x77;	// [계급]
	public static final int C_BOARD_LIST				= 0x78;	// 게시판 클릭 (현재 미사용 )
	public static final int C_BUY_SELL					= 0x7a;	// 상점 결과 처리
	public static final int C_ACCEPT_XCHG				= 0x7c;	// 교환 OK
	public static final int C_SLAVE_CONTROL				= 0x7D;	// 펫 공격 목표 지정 (현재 미사용 )
	public static final int C_SERVER_SELECT				= 0x82;
	public static final int C_MOVE						= 0x84;	// 이동요청 부분
	public static final int C_DELETE_CHARACTER			= 0x8a;	// 케릭터 삭제
	public static final int C_START_CASTING				= 0x8c;
	public static final int C_BOARD_DELETE				= 0x8e;
	public static final int C_EMBLEM					= 0x8f;	// 가시범위의 혈맹 마크 요청[폴더내 emblem삭제]
	public static final int C_SAVEIO					= 0x94;	// 캐릭인벤슬롯정보
	public static final int C_CANCEL_XCHG				= 0x96;	// 교환 취소
	public static final int C_CHANGE_CASTLE_SECURITY	= 0x97;	// 성내 치안 관리
	public static final int C_CHANGE_ACCOUNTINFO		= 0x9d;
	public static final int C_DEPOSIT					= 0x9e;	// 성 공금 입금
	public static final int C_INCLUDE					= 0xa2;
	public static final int C_REQUEST_ROLL				= 0xa5;
	public static final int C_THROW						= 0xa7;	// 낚시 종료
	public static final int C_ENTER_WORLD				= 0xa9;	// 리스창에서 케릭 선택
	public static final int C_QUERY_PERSONAL_SHOP		= 0xaa;	// 개인상점 buy, sell
	public static final int C_CLIENT_READY				= 0xab;	// 찾음[본섭]  (현재 미사용 )
	public static final int C_DUEL						= 0xac;	// [결투]
	public static final int C_HACTION					= 0xad;	// Npc 대화 액션 부분
	public static final int C_REMOVE_BUDDY				= 0xae;	// 친구삭제
	public static final int C_RESTART_COMPLETE			= 0xb0;	// 찾음[본섭] (사용안함_ )
	public static final int C_QUERY_BUDDY				= 0xb2;	// 친구리스트
	public static final int C_MONITOR_CONTROL			= 0xb6;
	public static final int C_SKILL_BUY					= 0xb7;	// skill buy
	public static final int C_WITHDRAW					= 0xb8;	// 공금 출금[자금을 인출한다]
	public static final int C_SUMMON					= 0xba;	// CALL버튼 .감시
	public static final int C_SMS						= 0xbb;
	public static final int C_NPC_ITEM_CONTROL			= 0xbd;
	public static final int C_USE_ITEM					= 0xbf;	// 아이템 사용 부분
	public static final int C_READ_NEWS					= 0xc0;	// 공지사항 확인 눌럿을때
	public static final int C_QUIT						= 0xc2;	// 종료
	public static final int C_USE_SPELL					= 0xc7;	// 스킬 사용 부분
	public static final int C_OPEN						= 0xc8;	// 문짝 클릭 부분.
	public static final int C_DEAD_RESTART				= 0xc9;	// 겜중에 죽어서 리셋 눌럿을때
	public static final int C_WHO_PLEDGE				= 0xca;	// [혈맹]
	public static final int C_MATCH_MAKING				= 0xcc;	// 찾음[본섭]  (현재 미사용 )
	public static final int C_BLINK						= 0xce;
	public static final int C_ASK_XCHG					= 0xd1;	// [교환]
	public static final int C_DIALOG					= 0xd2;	// Npc와 대화부분
	public static final int C_SELECTABLE_TIME			= 0xd5;
	public static final int C_BUYABLE_SPELL				= 0xd7;	// skill buy
	public static final int C_ONOFF						= 0xd8;	// [환경설정->전챗켬,끔].
	public static final int C_CHANGE_DIRECTION			= 0xda;	// 방향전환
	public static final int C_HYPERTEXT_INPUT_RESULT	= 0xdc;	// 수량성 아이템 제작 갯수
	public static final int C_EXTENDED_PROTOBUF			= 0xdd;	// 종합 패킷
	public static final int C_EXTENDED					= 0xdf;	// 아덴상점 아이콘 클릭, 부가 아이템, 혈맹창
	public static final int C_TITLE						= 0xe0;	// 호칭 명령어
	public static final int C_VOICE_CHAT				= 0xe3;	// 스텟 초기화.
	public static final int C_GET						= 0xe5;	// 아이템 줍기.
	public static final int C_ADD_BUDDY					= 0xe6;	// 친구추가
	public static final int C_EXIT_GHOST				= 0xea;	// 무한대전 관람모드 탈출
	public static final int C_LEAVE_PARTY				= 0xec;	// 파티 탈퇴
	public static final int C_LOGOUT					= 0xed;	// 다시 로긴창으로 넘어갈때 (현재 미사용)
	public static final int C_CHANGE_PASSWORD			= 0xee;
	public static final int C_ENTER_SHIP				= 0xef;	// 배탈때
	public static final int C_WAR						= 0xf2;	// 전쟁
	public static final int C_WISH						= 0xf5;
	public static final int C_SAVE						= 0xfb;
	
///////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////
	
	// server code
	public static final int S_CHARACTER_INFO			= 0x00;	// v 케릭터리스트의 케릭정보
	public static final int S_CHANGE_PASSWORD_CHECK		= 0x01;
	public static final int S_EXCHANGEABLE_SPELL_LIST	= 0x03;
	public static final int S_HYPERTEXT					= 0x04;	// Npc클릭 Html열람
	public static final int S_BUYABLE_SPELL_LIST		= 0x05;
	public static final int S_MAGE_STRENGTH				= 0x06;	// 힘업
	public static final int S_PARALYSE					= 0x07;	// 행동 제한 (커스패럴 상태) 사막 스콜피온한테 가서 커스당하기
	public static final int S_BOOK_LIST					= 0x08;
	public static final int S_MAGE_SHIELD				= 0x09;	// 쉴드
	public static final int S_MERCENARYSELECT			= 0x0d;	// 고용한 용병을 배치
	public static final int S_ACTION					= 0x0f;	// 액션 부분(맞는모습등)
	public static final int S_TAX						= 0x12;	// 세율 조정
	public static final int S_MOVE_OBJECT				= 0x13;	// 이동 오브젝트
	public static final int S_CHANGE_ALIGNMENT			= 0x14;	// 라우풀
	public static final int S_CHANGE_LIGHT				= 0x15;	// 밝기
	public static final int S_TIME						= 0x16;	// 게임 시간
	public static final int S_WAR						= 0x17;	// 전쟁
	public static final int S_CHANGE_ABILITY			= 0x1d;	// 이반, 소반 인프라 사용
	public static final int S_NOT_ENOUGH_FOR_SPELL		= 0x1f;
	public static final int S_NOTICE					= 0x23;	// 로그인후 패킷
	public static final int S_LOGIN_CHECK				= 0x25;	// 포탈이동시 날라오는 패킷(호런동굴들어갈때)확실치않음
	public static final int S_XCHG_START				= 0x26;	// 거래창 부분
	public static final int S_MAIL_INFO					= 0x27;	// 편지 읽기.
	public static final int S_HYPERTEXT_INPUT			= 0x2a;	// 수량성 아이템 제작 갯수 [여관]
	public static final int S_SLAVE_CONTROL				= 0x2c;	// 펫 공격 목표지정
	public static final int S_SELECTABLE_TIME_LIST		= 0x31;	// 공성시간 지정
	public static final int S_DELETE_CHARACTER_CHECK	= 0x32;	// 케릭 삭제
	public static final int S_MESSAGE					= 0x33;	// 시스템 메세지 (장사 채팅).
	public static final int S_CASTLE_OWNER				= 0x34;	// 성소유목록 세팅
	public static final int S_PLEDGE_WATCH				= 0x35;	// 혈맹 문장 주시
	public static final int S_MERCENARYNAME				= 0x37;
	public static final int S_XCHG_RESULT				= 0x3a;	// 거래 취소, 완료
	public static final int S_IDENTIFY_CODE				= 0x3d;	// 확인주문서
	public static final int S_MATCH_MAKING				= 0x3e;	// 찾음[본섭] (현재 미사용 )
	public static final int S_DECREE					= 0x3f;
	public static final int S_ADD_INVENTORY_BATCH		= 0x41;
	public static final int S_EFFECT_LOC				= 0x44;	// 트랩 (좌표위 이펙트)  포우 슬레이어로 따면 됨
	public static final int S_EXP						= 0x45;	// 경험치 갱신  (현재 미사용 )
	public static final int S_ADD_XCHG					= 0x46;	// 거래창 아이템 추가 부분 (현재 미사용 )
	public static final int S_DRUNKEN					= 0x47;	// 술, 드래곤진주
	public static final int S_READ_MAIL					= 0x48;	// 찾음[본섭]  (현재 미사용 )
	public static final int S_CHANGE_ATTR				= 0x49;	// 위치값을 이동가능&불가능 조작 부분
	public static final int S_FIXABLE_ITEM_LIST			= 0x4a;	// 무기수리 리스트
	public static final int S_EMOTION					= 0x4b;	// 용기
	public static final int S_BLINK						= 0x4e;
	public static final int S_VOICE_CHAT				= 0x51;	// v 스텟 초기화 길이
	public static final int S_RETRIEVE_LIST				= 0x56;	// 창고리스트
	public static final int S_HIT_POINT					= 0x57;	// HP 업데이트
	public static final int S_HIT_RATIO					= 0x59;	// 미니 HP표현 부분
	public static final int S_ADD_INVENTORY				= 0x5b;
	public static final int S_PERSONAL_SHOP_LIST		= 0x5c;
	public static final int S_REMOVE_OBJECT				= 0x5d;	// 오브젝트 삭제 (토글etc)
	public static final int S_CHANGE_LEVEL				= 0x5f;
	public static final int S_POISON					= 0x60;	// 독과 굳은 상태 : 표현 비취나 큐어포이즌 써보면 됨
	public static final int S_CHANGE_ITEM_DESC_EX		= 0x62;	// 인벤 아이템 갱신 0x62? 0x75?
	public static final int S_BUY_LIST					= 0x64;	// 상점 구입 부분[BUY]
	public static final int S_CHANGE_DESC				= 0x65;
	public static final int S_MAGIC_STATUS				= 0x66;	// sp와 mr변경
	public static final int S_CHANGE_COUNT				= 0x68;
	public static final int S_SAY_CODE					= 0x69;	// 샤우팅 글
	public static final int S_AC						= 0x6a;	// AC 및 속성방어 갱신 [블레스트 아머 사용시 나옴]
	public static final int S_NUM_CHARACTER				= 0x6b;	// v 해당 계정의 케릭 갯수
	public static final int S_CHANGE_DIRECTION			= 0x6c;	// 방향 전환 부분 [움직이는 엔피씨에 말걸어서 체크]
	public static final int S_CLIENT_READY				= 0x70;
	public static final int S_WITHDRAW					= 0x74;	// 공금 출금
	public static final int S_CHANGE_ITEM_DESC			= 0x75;	// 아이템 착용 (E표시) 0x62? 0x75?
	public static final int S_MERCENARYARRANGE			= 0x76;	// 선택한 용병 주기
	public static final int S_MERCENARYEMPLOY			= 0x77;	// 성 용병 고용
	public static final int S_ATTACK_ALL				= 0x78;
	public static final int S_MAGE_DEXTERITY			= 0x7d;	// 덱스업
	public static final int S_WARNING_CODE				= 0x7e;
	public static final int S_ASK						= 0x7f;	// [ Y , N ] 메세지
	public static final int S_DEPOSIT					= 0x82;	// 공금 입금
	public static final int S_CHANGE_ITEM_TYPE			= 0x87;
	public static final int S_MANA_POINT				= 0x8a;	// MP 업데이트
	public static final int S_WIELD						= 0x8b;	// 무기 착,탈 부분
	public static final int S_CHANGE_ITEM_USE			= 0x8c;
	public static final int S_NEW_CHAR_INFO				= 0x8d;	// 케릭 새로 만든거 보내기
	public static final int S_KICK						= 0x90;	// 해당 케릭 강제 종료
	public static final int S_ARCHERARRANGE				= 0x91;
	public static final int S_EFFECT					= 0x93;	// 이팩트 부분 (헤이스트등)
	public static final int S_CREATE_CHARACTER_CHECK	= 0x95;	// 캐릭터 생성시 처리부분
	public static final int S_BLIND						= 0x98;	// 눈멀기 효과
	public static final int S_INVISIBLE					= 0x99;	// 투명
	public static final int S_MASTER					= 0x9a;
	public static final int S_EVENT						= 0x9b;	// v 통합 패킷 관리 담당
	public static final int S_EXTENDED_PROTOBUF			= 0x9c;	// 종합 패킷
	public static final int S_PING						= 0xa1;
	public static final int S_NEWS						= 0xa3;	// 공지
	public static final int S_BOARD_READ				= 0xac;	// 게시판 읽기 (현재 미사용 )
	public static final int S_PORTAL					= 0xaf;	// 
	public static final int S_PLEDGE					= 0xb0;	// 클랜 업데이트, 아무 혈맹이나 가입하기
	public static final int S_ATTACK					= 0xb1;	// 공격 표현 부분
	public static final int S_WANTED_LOGIN				= 0xb2;
	public static final int S_TITLE						= 0xb8;	// 호칭 변경
	public static final int S_SERVER_LIST				= 0xba;
	public static final int S_SHOW_MAP					= 0xbc;
	public static final int S_CHANGE_ACCOUNTINFO_CHECK	= 0xbd;
	public static final int S_EXTENDED_HYBRID			= 0xbe;
	public static final int S_COMMAND_TARGET			= 0xc0;
	public static final int S_SPEED						= 0xc1;	// 헤이스트
	public static final int S_ROLL_RESULT				= 0xc3;
	public static final int S_PUT_OBJECT				= 0xc5;
	public static final int S_WORLD						= 0xc7;
	public static final int S_EMBLEM					= 0xc8;	// 클라에 혈문장 요청
	public static final int S_MESSAGE_CODE				= 0xc9;	// 서버 메세지[방어구중복으로체크]
	public static final int S_CHANGE_ITEM_BLESS			= 0xca;	// 봉인 주문서, 봉인줌서 사서 상아탑무기에 바르기
	public static final int S_ATTACK_MANY				= 0xcd;	// 파톰 어퀘등의 스킬
	public static final int S_VERSION_CHECK				= 0xce;
	public static final int S_REQUEST_SUMMON			= 0xcf;	// 텔레포트[손바닥]
	public static final int S_SOUND_EFFECT				= 0xd2;	// 사운드 이팩트 부분[펫 호루라기로 찾기]
	public static final int S_CLONE						= 0xd3;
	public static final int S_ENTER_WORLD_CHECK			= 0xda;	// 접속담당
	public static final int S_ADD_SPELL					= 0xdb;
	public static final int S_ABILITY_SCORES			= 0xdf;	// 스테이터스 갱신(디크리즈,민투)
	public static final int S_ADD_BOOKMARK				= 0xe0;	// 기억 리스트
	public static final int S_AGIT_MAP					= 0xe1;
	public static final int S_RESTART					= 0xe2;	// 찾음[본섭]
	public static final int S_BOARD_LIST				= 0xe3;
	public static final int S_RESURRECT					= 0xe8;	// 부활 처리 부분
	public static final int S_WEATHER					= 0xeb;	// 날씨 조작하기
	public static final int S_CRIMINAL					= 0xec;	// 보라돌이
	public static final int S_REMOVE_SPELL				= 0xed;
	public static final int S_SELL_LIST					= 0xf0;	// 상점에 판매 부분
	public static final int S_EXTENDED					= 0xf2;	// 아덴상점생존의 외침 등등
	public static final int S_AGIT_LIST					= 0xf3;	// 아지트 리스트
	public static final int S_REMOVE_INVENTORY			= 0xf6;	// 인벤토리 아이템 삭제
	public static final int S_BREATH					= 0xf8;	// 에바 아이콘 
	public static final int S_SAY						= 0xf9;
	public static final int S_STATUS					= 0xfc;	// 케릭 정보 갱신
	
///////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////
	
	// first code
	public static final int FIRST_KEY					= 0x20;	// 최초 패킷
}

